Feat/#18 게시물 좋아요 기능 구현
f-lab-edu/Prostargram pull request #25
Opened 2023-08-04 16:30 UTC by eunbileeme

## 📢 관련 이슈
- [x] #18 

## 📃 작업 사항
- 게시물 좋아요 기능 구현

## ✔️ 체크 포인트
### (2023.08.05)
- LikeController, LikeService, LikeMapper 구현 완료했습니다.

### (2023.08.08)
- 각 클래스의 위에 선언하는 어노테이션의 (관례상) 작성 기준이 있는지 궁금합니다.
- LikeController의 Unit Test로 @WebMvcTest(controllers = LikeController.class)가 적합하지 않은 이유가 아직 이해되지 않았습니다.
- addPostLike()의 Unit Test 진행 중, `DB 연결 문제 상황'을 단위 테스트의 시나리오에 넣는게 맞는지 고민이 됩니다.
```
@DisplayName("DB 연결 문제로 LikeMapper 호출 중 에러 발생 시 테스트")
@Test
void dbConnectionErrorWhileCallingLikeMapper() {
    //given
    long postId = 1L;
    long userId = 2L;

    // Mock the mapper behavior to throw an exception simulating DB connection issue
    when(likeMapper.addPostLike(postId, userId)).thenThrow(new RuntimeException("DB connection error"));

    // when then
    assertThatThrownBy(() -> likeService.addPostLike(postId, userId))
        .isInstanceOf(RuntimeException.class)
        .hasMessageContaining("DB connection error");
}
```
- `import static org.assertj.core.api.Assertions.assertThatCode;`와
`import static org.assertj.core.api.AssertionsForClassTypes.assertThatCode;`의 차이가 궁금합니다.
`assertThat`이 필요한 상황에서 alt + enter를 통해 module을 import 하는 경우 후자의 module이 import 되는 이유도 궁금합니다.
- LikeServiceUnitTest에서 정상적으로 로직이 처리되는지 확인하는 validlikeService.addPostLike에서 `likeService.addPostLike(postId, userId);`와 `assertThatCode(() -> likeService.addPostLike(postId, userId)).doesNotThrowAnyException();`의 차이가 궁금합니다.
- ResponseEnum의 code(Field name)이 HTTP status code와 가끔 혼동되는데, 바꿔야할 필요가 있을지 멘토님의 의견이 궁금합니다.
- Unit Test와 Integration Test의 범주가 약간 헷갈립니다.
예를 들어, "게시물 좋아요 기능"에 대해 LikeService를 Test하는 상황이라고 가정해보겠습니다.
Integration Test에서 잘못된 postId 또는 userId 값(= 음수)이 들어올 경우를 테스트하는 건 적합하지 않나요?
- LikeService - Integration Test 시에 값을 지정해서 진행하는 건, 언젠가 그 값을 가질 경우가 발생할 수도 있을텐데(= 이 경우, Integration Test를 진행하는 의미가 퇴색된다고 생각합니다) 더 나은 방향으로 테스트하기 위해 어떤 방법이 있나요?

### (2023.08.16)
- 컨트롤러의 단위 테스트 코드에서는 값을 줄 때, `postId1` 변수로, 서비스 단위 테스트 코드에서는 값을 줄 때 `invalidpostId`와 같이 변수명을 짓고 줬었습니다. 혹시 뚜렷한 이유가 있을까요?
- 컨트롤러 유닛 테스트를 작성할 때, 음수값 같은 경우는 정상적인 경로로 들어오는 값이 아닌데 원래 이런 경우도 포함해서 테스트를 진행하는게 맞나요?
   - 각각의 레이어에서 테스트를 하고자 하는 것의 범위를 잡기가 어려운 것 같아요.
- 컨트롤러 테스트(ex. validation) vs 서비스 테스트(ex. 유저가 할법한 행동들)
- 서비스 레이어에서는 통합 테스트가 의미가 없다고 하셨었는데, 다른 JPA에서는 서비스 레이어에 대해 통합 테스트를 진행하는 코드를 본 적이 있어요. 혹시 JPA의 경우에는 서비스 레이어에 대해 통합 테스트가 필요한가요?
- 이전에 디자인 패턴은 외운다기보다 '이게 ~~한 디자인 패턴이었구나'라는 식으로 디자인 패턴을 이해하게 된다고 하셨습니다. 그런데 디자인 패턴을 잘 모르는 상황에서는 알 수 없거나 민욱님처럼 '`facade 패턴`을 써야지!'하고 쓰시는 경우가 많던데, 위 경우들은 디자인 패턴을 알고는 있는 상황에서 진행된다는 가정하에 말씀하신게 맞을까요?
- 최종 PR 단계에 웬만하면 코드에 주석을 남기지 않는 것이 일반적인 것 같은데, 헷갈리거나 생소한 기능에 대해서도 주석을 남기고 진행하는걸 추천하지 않으시나요?
- 현재 에프랩의 여러 레포에서 코드를 참고하고 있는데, 제가 코드를 작성하는 환경과 참고하는 코드가 작성된 환경이 다른 경우가 대부분입니다. 이때, 멘토님께서는 해당 코드의 어느 부분을 참고하는지가 궁금합니다.
- 이력서에 작성하는 기술적인 이슈들은 어떤 기준에 의해서 기재하는지 궁금합니다.
- 이전에는 코드를 어떤 방식으로든 작성하고 나서, "왜 이렇게 쓰였는지"에 대해서 알면 된다고 하셨습니다. 그런데, 이해와 작성은 별개라고 생각이 됩니다. 예를 들어, 저는 gpt에게 제공받은 코드를 위주로 수정 및 이해를 진행하는데, 실무에서는 불가능한 공부 방향이 아닌가 싶어요. 그리고 실무에서도 이미 제공되어 있는 코드를 기반으로 작성하게 되는게 맞나요?
- ※ Long, long (코드 참고 바람)

2023-08-04 21:44 UTC, f-lab-jason reviewed
상당량이 이전의 #6과 중복인 것 같은데, slack에서 말씀드린것처럼 정리를 하면 좋겠네요 :)
controller와 service에 대한 테스트도 추가해주시겠어요?

2023-08-04 21:44 UTC, f-lab-jason commented on src/main/java/flab/project/controller/LikeController.java
> +    public SuccessResponse addPostLike(@PathVariable("postId") long postId, @PathVariable("userId") long userId) {
입력값의 validation은 다른 PR에서 하실 예정인가요?

2023-08-04 21:44 UTC, f-lab-jason commented on src/main/java/flab/project/service/LikeService.java
> +        }
민욱님 리뷰에서도 말씀드렸던 것 같은데 이런 일반 exception 처리는 각 로직마다 하는것 대신에 exception handler에서 해주면 더 좋겠습니다.

2023-08-07 06:41 UTC, eunbileeme commented on src/main/java/flab/project/controller/LikeController.java
> +    public SuccessResponse addPostLike(@PathVariable("postId") long postId, @PathVariable("userId") long userId) {
넵, 맞습니다! 지금은 Controller의 틀만 작성하여 올릴 예정이고, 추후에 이 PR에 추가하게 된다면 commit 전 comment를 남기도록 하겠습니다.

2023-08-08 17:20 UTC, eunbileeme commented
(2023.08.08)
LikeController에 대한 Unit Test의 경우, @WebMvcTest의 사용이 적합하지 않은 이유를 이해하지 못했기에 작성하지 않았습니다.
Integration Test는 멘토링 전까지 올려보도록 노력하겠습니다 😅

### 멘토님의 피드백
1. LikeService - Unit Test, Integration Test 작성
2. LikeController - 입력값에 대한 validation 추가
3. exception handler 추가
4 .. 등등

완료하였습니다.

2023-08-09 11:06 UTC, J-MU commented on src/test/java/flab/project/service/LikeServiceIntegrationTest.java
> +
"사용자가 여러 피드에 좋아요 추가"라는 테스트 코드가 검증하고 싶은게 뭔가요? 사용자가 "하나의 피드"에 좋아요를 때랑 사용자가 여러 피드에 좋아요를 할 때랑 아무런 차이가 없어서 하나의 피드에 좋아요를 추가할 수 있으면 여러 피드에 좋아요는 당연히 가능할텐데, 해당 테스트 코드가 왜 필요한지 잘 모르겠습니다.

2023-08-15 08:23 UTC, eunbileeme commented on src/test/java/flab/project/service/LikeServiceIntegrationTest.java
> +
원래는 막연하게 "딜레이에 의해 사용자가 한 게시물에 좋아요를 누를 때랑, 여러 게시물 - 즉 피드에 동시에 좋아요를 누를 경우 좋아요가 반영이 안 될 수도 있지 않을까?" 싶어서 작성한 코드였습니다.

말씀하신대로 하나의 게시물에 좋아요를 추가할 수 있다면, 피드에도 좋아요를 추가할 수 있을 것 같네요.

그래도 서버에 동시다발적으로 여러 요청이 쌓였을 경우, 서버가 처리를 하다가 중단이 발생하는 경우가 있을 거라고 생각되는데 위와 같은 상황(= 사용자가 피드에 좋아요를 누르는 상황)에 대해 테스트를 진행해야 하지 않을까요? 이것 또한 별개의 상황인지 궁금합니다.

2023-08-17 02:28 UTC, f-lab-jason requested changes

2023-08-17 02:28 UTC, f-lab-jason commented on src/main/java/flab/project/ApiControllerAdvice/ApiControllerAdvice.java
> +        System.out.println("ApiControllerAdvice.exceptionResolveToInvalidUserInput");
nit: `system.out.println`들은 제거해주세요

2023-08-17 02:28 UTC, f-lab-jason commented on src/main/java/flab/project/config/baseresponse/ResponseEnum.java
> +    INVALID_USER_INPUT(false, 4000, "올바르지 않은 경로의 요청입니다."),
nit: 'INVALID_USER_INPUT'인데 '올바르지 않은 경로의 ...'가 맞는 메세지인가요..?

2023-08-17 02:28 UTC, f-lab-jason commented on src/main/java/flab/project/controller/LikeController.java
> +    public SuccessResponse addPostLike(@PathVariable("postId") @Positive long postId, @RequestParam("userId") @Positive long userId) {
`userId`를 입력으로 받을 필요가 있나요? 로그인된 유저 정보를 쓸거라 예상해서 여쭤봅니다

2023-08-17 02:28 UTC, f-lab-jason commented on src/test/java/flab/project/controller/LikeControllerTest.java
> +        given(likeService.addPostLike(postId2, userId2)).willThrow(new InvalidUserInputException("postId 또는 userId는 0보다 커야 합니다."));
이건 실제로 `likeService`의 호출이 일어나야 원하는 결과를 받을텐데 음수로 컨트롤러를 요청한 경우는 컨트롤러의 `@Positive`때문에 `likeService`를 호출하기도 전에 파라미터를 파싱하면서 에러를 뱉는걸로 보이네요.

2023-08-17 07:54 UTC, J-MU commented on src/test/java/flab/project/service/LikeServiceIntegrationTest.java
> +
은비님이 말씀 하신 경우는 userId와 postId가 복합키로 선언만 잘 되어있으면  DB단에서 DupliateKeyException이 던져질거에요. 해당 Exception을 잘 캐치해서 핸들링하는지를 테스트 해주면 될 거 같네요.

2023-08-17 07:54 UTC, J-MU commented on src/main/java/flab/project/mapper/LikeMapper.java
> +    int addPostLike(@Param("post_id") long postId, @Param("user_id") long userId);
@Param안에를 스네이크 케이스로 작성하신 이유가 따로 있나요?

2023-08-17 07:54 UTC, J-MU commented on src/main/java/flab/project/controller/LikeController.java
> +    }
PathVariable의 userId는 뭔가요? URL상에서는 userId가 나타나지 않아서요

2023-08-17 07:54 UTC, J-MU commented on src/test/java/flab/project/service/LikeServiceTest.java
> +    }
음수인 경우만 잘못된 값이 아니라 0인 경우도 잘못된 값이잖아요? 0도 테스트 해주는게 좋을 거 같습니다

2023-08-17 08:01 UTC, eunbileeme commented on src/main/java/flab/project/controller/LikeController.java
> +    }
아, VoteController에서만 수정하고 여기서 수정하진 않았군요.. 짚어주셔서 감사합니다.
@PathVariable - > @RequestParam으로 수정 예정입니다.

2023-08-17 08:02 UTC, eunbileeme commented on src/main/java/flab/project/config/baseresponse/ResponseEnum.java
> +    INVALID_USER_INPUT(false, 4000, "올바르지 않은 경로의 요청입니다."),
잘못 이해한 상태에서 적었던 메세지인 것 같습니다. 수정하도록 하겠습니다!

2023-08-17 08:03 UTC, eunbileeme commented on src/main/java/flab/project/controller/LikeController.java
> +    public SuccessResponse addPostLike(@PathVariable("postId") @Positive long postId, @RequestParam("userId") @Positive long userId) {
넵, 맞습니다. 원래는 인증 토큰(JWT)에서 가져와서 사용하려고 했었는데, 아직 구현이 안 된터라 임시로 userId를 가져오는 방식으로 작성하게 되었습니다.

Todo로 기재해두도록 하겠습니다.

2023-08-21 10:46 UTC, eunbileeme commented on src/test/java/flab/project/service/LikeServiceIntegrationTest.java
> +
서버단에 많은 요청이 쌓여서 중단이 발생되는 경우가 왜 DupliateKeyException과 관련이 있는지 보충 설명가능할까요?
DupliateKeyException은 말 그대로 중복 키 요청에 의해서 발생하는 예외 같은데, 왜 관련이 있는지 잘 모르겠어요 😅

2023-08-21 10:46 UTC, eunbileeme commented on src/main/java/flab/project/ApiControllerAdvice/ApiControllerAdvice.java
> +        System.out.println("ApiControllerAdvice.exceptionResolveToInvalidUserInput");
혹시 e.printStackTrace();와 동일한 역할을 수행하기 때문이 맞을까요?

2023-08-21 10:54 UTC, eunbileeme commented on src/test/java/flab/project/controller/LikeControllerTest.java
> +        given(likeService.addPostLike(postId2, userId2)).willThrow(new InvalidUserInputException("postId 또는 userId는 0보다 커야 합니다."));
1. 헉.. 그럼 위와 같은 경우는 어떤 식으로 코드를 수정해야 하나요?
어쨌든 지금 이 메서드에서는 "잘못된 값이 들어왔을 때, 예상한 예외가 던져지는지"를 테스트해야 하는데, 컨트롤러에서 @Positive를 지우고 싶진 않아서 여쭤봅니다.

2. 혹시 위 에러의 원인을 어떻게 알아내셨나요?
저는 디버그를 할 때, 위 given절에 브레이크 포인트를 찍어서 확인했음에도 불구하고 동일한 에러만 발생하여 원인을 알아내기 힘들었네요 😂
다음 번에는 제가 제대로 원인을 파악했으면 해서 여쭤봅니다!

2023-08-21 11:16 UTC, eunbileeme commented on src/main/java/flab/project/mapper/LikeMapper.java
> +    int addPostLike(@Param("post_id") long postId, @Param("user_id") long userId);
오.. 일단 [Mapper 인터페이스의 정의](https://twofootdog.github.io/Spring-DAO%EC%99%80-Mapper%EC%9D%98-%EC%B0%A8%EC%9D%B4%EC%A0%90/)는 "Mybatis 매핑XML에 기재된 SQL을 호출하기 위한 인터페이스"죠.
그래서 무의식적으로 DB 필드와 일치시키기 위해서 스네이크 케이스로 작성한 것 같아요.

혹시 일반적으로 카멜 케이스로 작성하나요?

2023-08-21 12:51 UTC, J-MU commented on src/main/java/flab/project/mapper/LikeMapper.java
> +    int addPostLike(@Param("post_id") long postId, @Param("user_id") long userId);
자바 코드니까 카멜 케이스로 작성했고 제가 검색하면서 봤던 다른 코드도 카멜 케이스였던거 같아서 여쭤봤습니다.

2023-08-21 12:51 UTC, J-MU commented on src/test/java/flab/project/controller/LikeControllerTest.java
> +        given(likeService.addPostLike(postId2, userId2)).willThrow(new InvalidUserInputException("postId 또는 userId는 0보다 커야 합니다."));
해당 테스트 코드를 실제로 실행시켜 보면 에러메시지가 발생합니다. 해당 에러메시지를 잘 보면 
jakarta.servlet.ServletException: Request processing failed: jakarta.validation.ConstraintViolationException: addPostLike.arg0: must be greater than 0, addPostLike.arg1: must be greater than 0
와 같은 문구가 있습니다.
ConstraintViolationException은 pathVariable을 매핑하는 과정에서 @Positive 제약 조건에 위반되어 던져진 예외입니다.
반면, ControllerAdvice를 확인해보시면 해당 예외를 핸들링 하는 부분이 없어요. 따라서 Spring은 기본 에러 처리 과정에 따라 예외가 발생했으니 500 http status code를 붙여 반환하게 될 거에요.

2023-08-22 06:52 UTC, eunbileeme commented on src/main/java/flab/project/mapper/LikeMapper.java
> +    int addPostLike(@Param("post_id") long postId, @Param("user_id") long userId);
이해했습니다, 카멜 케이스로 수정하도록 할게요!

2023-08-25 00:29 UTC, J-MU commented on src/test/java/flab/project/service/LikeServiceIntegrationTest.java
> +
말씀하신 내용을 오해했습니다.
제가 말씀드린 부분은 하나의 postId에 대해서 유저가 여러번 요청을 보낸 경우를 말씀드린 거였어요.
서버 단에 많은 요청이 쌓여서 중단이 발생되는 경우는 단위 테스트가 아닌 성능테스트에서 이뤄져야 하는 부분이라고 보며, 단위테스트에서 이를 검증할 방법은 없을거 같네요.

2023-08-25 01:31 UTC, f-lab-jason commented on src/main/java/flab/project/ApiControllerAdvice/ApiControllerAdvice.java
> +        System.out.println("ApiControllerAdvice.exceptionResolveToInvalidUserInput");
그것도 있지만 저희 세션때 `system.out.println`은 절대 프로덕션 코드로 나가서는 안되는 친구라고 얘기했었는데 왜인지 한 번 찾아보시면 좋겠습니다 :)

2023-08-25 01:34 UTC, f-lab-jason commented on src/test/java/flab/project/controller/LikeControllerTest.java
> +        given(likeService.addPostLike(postId2, userId2)).willThrow(new InvalidUserInputException("postId 또는 userId는 0보다 커야 합니다."));
1. 컨트롤러를 테스트하는거기때문에 현재 컨트롤러에서 500을 뱉는건 정상이고, 그러면 500으로 테스트를 수행하는게 맞습니다.
2. likeService까지 갔다면 원하는 400이 나왔겠지만 500이 나왔으니 그 전에 에러를 뱉었다는 얘기고, 그러면 주어진 입력에서 컨트롤러가 에러를 낼만한 부분이 어딘지를 생각해보면 좋을 것 같아요.

2023-09-01 00:00 UTC, f-lab-jason approved these changes

2023-09-01 00:00 UTC, f-lab-jason commented on src/test/java/flab/project/controller/LikeControllerTest.java
> +        // Todo IllegalArgumentException: Not enough variable values available to expand 'postId'
이 부분은 세션때 얘기했던거 같은데 이 PR에서 정리하셔도 좋고 따로 PR을 만드셔도 좋습니다.

2023-09-03 16:07 UTC, J-MU approved these changes

2023-09-03 16:08 UTC, merged