Feat/#65 댓글 가져오기 기능 구현
f-lab-edu/Prostargram pull request #67
Opened 2023-10-31 16:40 UTC by eunbileeme

## 📢 관련 이슈
- [x] #65 

## 📃 작업 사항
- 작업 사항

2023-11-01 01:09 UTC, J-MU commented on src/main/java/flab/project/controller/CommentController.java
>                                                 @RequestParam("content") @NotBlank String content) {
1. 댓글 길이 제한 1000자에 대한 검증이 반영되지 않은 거 같습니다. [slack 대화 기록 참고](https://f-lab-edu.slack.com/archives/C05CU90P8BV/p1696997470394479?thread_ts=1696948584.132559&cid=C05CU90P8BV)
2. content를 queryParam으로 받게 되면 URL이 지저분해 보인다는 점 때문에 저라면 DTO로 postId, userId, content를 받을 거 같아요. 큰 문제는 아닌거 같긴 한데  content가 URL상에 노출 되는게 저한테는 이상하게 느껴지네요.

2023-11-01 01:09 UTC, J-MU commented on src/main/java/flab/project/service/CommentService.java
> +    private void validateComment(long postId, Long parentId) {
왜 content는 검증하지 않나요?

2023-11-01 01:09 UTC, J-MU commented on src/main/java/flab/project/controller/CommentController.java
> +                                                             @RequestParam(defaultValue = "10") @Positive long limit) {
1. limit은 유저가 보내는게 아니라 저희가 상수로 가지고 있어야 하지 않을까요? 물론 defaultValue를 주시긴 했지만 "유저가 보낼 수 있다"자체가 이상적이진 않은거같아요. 유저가 임의로 limit을 엄청 큰 값으로 줄 수도 있으니까요.
2. getComments

2023-11-01 01:09 UTC, J-MU commented on src/main/resources/mapper/flab/project/mapper/comment-mapper.xml
> +
No-Offset 방식을 사용하셨군요. 저는 No-Offset방식을 몰랐는데 덕분에 배웠습니다. 감사합니다.

<<질문>>
1. CDATA를 부등호가 있는 부분만 감싸지 않고 Where문 전체를 감싸신 이유가 뭔가요?
2. CommentWithUser와 매핑하기 위해선 resultMap이 필요할거 같아요.
3. lastCommentId가 없으면 어떻게 되나요? (처음 조회하는 경우)

2023-11-01 01:09 UTC, J-MU commented on src/main/java/flab/project/service/CommentService.java
> +    public List<CommentWithUser> getComment(long postId, long lastCommentId, long limit) {
getComments

2023-11-01 01:25 UTC, J-MU commented on src/main/java/flab/project/data/dto/CommentWithUser.java
NoArgsConstructor + Getter조합이 아니라 AllArgsConstructor를 이용하신 이유가 있나요?

2023-11-01 01:34 UTC, J-MU commented on src/main/resources/mapper/flab/project/mapper/comment-mapper.xml
>      </insert>
parentId는 왜 사용되지 않나요?

2023-11-01 04:48 UTC, eunbileeme commented on src/main/java/flab/project/service/CommentService.java
> +    private void validateComment(long postId, Long parentId) {
content에 대한 검증이라면 욕설과 같은 필터링을 말씀하는게 맞으실까요?

2023-11-01 07:21 UTC, J-MU commented on src/main/java/flab/project/service/CommentService.java
> +    private void validateComment(long postId, Long parentId) {
아뇨 컨트롤러단에서 @NotBlank 어노테이션을 작성하셨으니 Service단에서도 검증해야 할 거 같아서요.
위에서 말씀드린 댓글 길이제한 1000자도 같이 검증하시면 좋을거같아요.

2023-11-02 07:03 UTC, eunbileeme commented on src/main/resources/mapper/flab/project/mapper/comment-mapper.xml
> +
1. CDATA 문법을 참고한 레퍼런스에서 SQL문 전체에 걸거나 아니면 조건문에 거는 걸 제안하고 있었어요.
따라서 부등호를 조건문이 아닌 다른 부분에 추가할 일이 없을 것 같아서 Where문에 추가를 했습니다.
하지만, 물어보신 것처럼 그냥 AND문만 감싸는게 자연스러운 것 같아서 수정할 예정입니다.

2. 헉 짚어주셔서 감사합니다.
Response Body에서 null만 담기길래, 'DB에서 데이터를 가져오는 과정 중에 문제가 생긴 것 같은데?'만 생각 중이었는데.. resultType과 매핑이 잘 안 되어서 그랬던 거군요. 추가하겠습니다.

3. 고려하지 못 했던 부분인데, 감사합니다.
lastCommentId가 없는 경우는 말씀하신 것처럼 "처음 조회하는 경우"이므로 조건문에 의해 그냥 최신 10개의 댓글을 가져오는 것으로 처리하겠습니다.

2023-11-02 07:04 UTC, eunbileeme commented on src/main/java/flab/project/data/dto/CommentWithUser.java
기본 생성자가 없으면 발생하는 오류 때문에, 기존에 있는 매개변수 생성자에 기본 생성자를 추가해주기 위해 AllArgsConstructor를 사용했습니다.

2023-11-02 07:05 UTC, eunbileeme commented on src/main/resources/mapper/flab/project/mapper/comment-mapper.xml
>      </insert>
오.. 수정하겠습니다. 당시에 최상단의 댓글만 고려하고 짠 로직인가보네요.

2023-11-06 07:01 UTC, J-MU commented on src/main/resources/mapper/flab/project/mapper/comment-mapper.xml
> +
1. SQL문 전체에 거는 것도 좋은 방법 인거 같은데 선택하지 않으신 이유가 뭔가요?

2023-11-06 07:09 UTC, eunbileeme commented on src/main/resources/mapper/flab/project/mapper/comment-mapper.xml
> +
우선 CDATA를 사용하는 이유는 쿼리를 작성할 때, '<', '>', '&'를 태그가 아닌 연산자로 올바르게 인식하기 위해 사용하는 문법이죠.

따라서 아래의 이유들로 조건문(= Where 내부의 AND)에만 CDATA를 붙여야겠다고 생각했어요.
1. 연산자를 올바르게 인식시켜주기 위해 필요로 하는 곳(= 조건문)에만 CDATA를 붙이는게 적합하다고 생각
2. 조건문을 제외한 다른 부분에서 부등호와 같은 연산자를 추가할 일이 있을까? 라고 생각해봤을 때, 없을거라고 생각

2023-11-06 07:15 UTC, J-MU commented on src/main/resources/mapper/flab/project/mapper/comment-mapper.xml
> +
네 저도 조건문 외에는 부등호와 같은 연산자를 추가할 일이 없을거 같아요. 제가 SQL문 전체에 CDATA를 거는 것이 더 좋을거 같다고 생각한 이유는 SQL문 중간에 CDATA와 같은 부가적인 코드가 노출되지 않으면 가독성이 더 좋다고 생각해서입니다.
```
SELECT *
        FROM COMMENT
        <![CDATA[
        WHERE post_id = #{postId}
          AND comment_id < #{lastCommentId}
        ]]>
        ORDER BY comment_id DESC
        LIMIT #{limit}
```
위 코드에서는 조건절에 SQL문이 아닌 Mapper에서 Escape처리를 위한 코드가 끼어들어 있어 SQL문을 읽는데 방해가 된다고 느껴집니다.
```
<![CDATA[
        SELECT *
        FROM COMMENT
        WHERE post_id = #{postId}
          AND comment_id < #{lastCommentId}
        ORDER BY comment_id DESC
        LIMIT #{limit}
  ]]>
```
반면 이렇게 처리하면 SQL문을 읽는데 방해된다는 느낌이 사라져서 아래와 같은 형태가 더 이상적이라고 느껴지는데 은비님이 느끼시기엔 어떤가요?

2023-11-06 07:29 UTC, eunbileeme commented on src/main/resources/mapper/flab/project/mapper/comment-mapper.xml
> +
오호, 저도 후자가 가독성이 좋은 것 같다고 생각이 들어요.

그런데, 혹시 아래와 같이 수정했을 때는 첫 번째 케이스와 동일한 정도의 방해된다는 느낌이 드실까요?
- 민욱님과 멘토님께서 조언해주신 것처럼 WHERE 내부의 AND문에만 CDATA가 걸리도록 수정
- lastCommentId가 없을 경우, 그냥 최신 10개의 댓글을 가져오도록 수정
```
    <select id="findAllByPostId" resultType="CommentWithUserMap">
        SELECT *
        FROM COMMENT
        WHERE post_id = #{postId}
          <if test="lastCommentId != null">
          <![CDATA[
          AND comment_id < #{lastCommentId}
        ]]>
        </if>
        ORDER BY comment_id DESC
        LIMIT #{limit}
    </select>
```
저는 CDATA를 처음 써보기 때문에, 단순히 민욱님의 의견이 궁금해서 질문드립니다.

그리고 if 조건문이 존재함에 따라 CDATA를 제거해도 if 조건문이 남으므로, AND 조건문 이전에 결이 다른 SQL이 있는 건 동일하다고 느껴질 수도 있지 않을까?싶어서 여쭤보아요.

2023-11-06 07:42 UTC, J-MU commented on src/main/resources/mapper/flab/project/mapper/comment-mapper.xml
> +
1. 네 방해된다고 느끼긴 합니다.
2. 
>그리고 if 조건문이 존재함에 따라 CDATA를 제거해도 if 조건문이 남으므로, AND 조건문 이전에 결이 다른 구문이 있는 건 동일하다고 느껴질 수도 있지 않을까?

Mybatis에서 동적 쿼리문을 작성할 때, 가독성이 떨어지는 점은 myBatis의 한계라고 생각합니다. 어쩔 수 없는거 같아요.

3. if문과 같은 태그는 제가 생각을 못하고 SQL문 전체를 CDATA로 감싸는 것을 제안 드렸는데, SQL문 전체를 CDATA로 감싸면 if문과 같은 태그도 동작 하지 않을거 같네요. 혹시 테스트 해보셨나요?
만약 정상 동작 하지 않는다면 어쩔 수 없이 위에 올려주신 코드가 최선일 거 같습니다.

4. 저도 CDATA처음 봐서 은비님 의견이 궁금했습니다. 의견 자유롭게 말씀해주세요.

2023-11-07 00:28 UTC, J-MU requested changes

2023-11-07 00:28 UTC, J-MU commented on src/main/java/flab/project/controller/CommentController.java
> +        if (limit > MAX_LIMIT) {
1. 해당 검증을 Annotation방식이 아닌 직접 if문으로 처리하신 이유가 뭔가요?
2.  limit을 유저가 전송하는 형태를 유지하고 계신데 이유가 궁금합니다.

2023-11-07 00:28 UTC, J-MU commented on src/main/java/flab/project/service/CommentService.java
> +    }
Controller단에서는 content에 대한 검증을 @NotBlank 어노테이션으로 검증하고 계시는데 여기 서는 공백 문자열에 대한 검증이 누락된 거 같습니다.

@NotBlank 어노테이션의 경우 아래와 같은 경우를 모두 불허 합니다.
1. null
2. ""(빈 문자열)
3. "           " (공백 문자열)

은비님은 위 경우 중 3번 케이스를 누락하셨어요. 해당 부분 검증을 추가 해주셔야 할 듯 합니다.
다만 이를 직접 작성하기 보다는 StringUtils 클래스의 isBlank메서드를 사용하는 것을 추천드립니다.

![image](https://github.com/f-lab-edu/Prostargram/assets/46997074/2c8f740a-2422-4841-8002-d7c07895e3b6)

[공식문서 바로가기](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#isBlank-java.lang.CharSequence-)

2023-11-07 06:49 UTC, eunbileeme commented on src/main/java/flab/project/controller/CommentController.java
> +        if (limit > MAX_LIMIT) {
우선, 이 부분은 세션 때 멘토님께 피드백을 받은 방향으로 수정을 진행했습니다.

(1)
어노테이션이라면 @Min, @Max와 같은 어노테이션을 말씀하신 걸까요?
일단 if문으로 처리한 이유는 throw를 던지기 위해서 사용했습니다.

(2) + (3)

-1.  limit의 기본값이 10이고, 해당 값은 경우에 따라 10미만의 값 또는 10을 초과한 값을 들어올 수가 있기 때문에 MAX_LIMIT을 설정해두었습니다.
-2. 말씀하시는 유저는 클라이언트를 말씀하시는게 맞을까요?
이와 별개로, (1)에서 말씀드린 것처럼 limit의 값은 경우에 따라 10이 아닐 수도 있기 때문에, 값을 받아와서 검증하는 식으로 진행했어요,

기본적으로 limit는 10이죠.
즉, lastCommentId가 31이라면 30~21개의 댓글을 가져오는 식으로 진행하기 위해 limit는 10으로 설정했어요.

그런데, limit의 default 값이 10일 뿐이고 댓글이 10개 이하로 있다면 limit의 값은 10 이하의 값으로 서버에 전달될 수가 있어요.

또한, 반대로 만약 limit의 값이 10을 초과해서 서버로 전달되었다면
(1) 잘못된 limit 값으로 판단하고 Exception을 던지거나
(2) Math.min(limit, MAX_LIMIT)으로 강제로 10으로 업데이트
해주는 방식으로 진행해야 해요.

따라서 위 일련의 이유들로 인해, 우선 limit를 받아오고 올바르지 않은 값이라면 Exception을 던지기 위해 아래와 같이 구현했습니다.
- limit를 클라이언트로부터 받아옴
- 비교 대상인 MAX_LIMIT를 설정
- 조건문으로 판별

2023-11-07 07:07 UTC, J-MU commented on src/main/java/flab/project/controller/CommentController.java
> +        if (limit > MAX_LIMIT) {
1. ConstraintsViolationException이 던져질 텐데, 현재 이미 RestControllerAdvice에서 INVALID_USER_INPUT을 담은 FailResponse를 던지는 형태로 구현되어 있는데 은비님 구조에서 처럼 수동으로 하는게 더 나은 점이 있나요?
2. 보여줄 남은 댓글의 개수가 8개일 때, LIMIT이 10인게 문제가 있나요?

2023-11-08 15:25 UTC, eunbileeme commented on src/main/java/flab/project/controller/CommentController.java
>                                                 @RequestParam("content") @NotBlank String content) {
![image](https://github.com/f-lab-edu/Prostargram/assets/103405457/edb87124-6ea6-4ea6-b1c5-127026acd1a2)

2. 많이 지저분해 보이는군요.. Response Body만 보다보니 잘 몰랐었는데, 감사합니다. Dto로 빼두는 방향으로 진행하도록 할게요.

2023-11-08 15:30 UTC, eunbileeme commented on src/main/resources/mapper/flab/project/mapper/comment-mapper.xml
> +
1 + 2.
그렇군요, 어쩔 수 없는 부분이군요.
그럼 if 동적 쿼리문만 있든, 아니면 if 동적 쿼리문 + CDATA가 같이 있든 동일한 정도로 방해된다고 말씀하시는게 맞으실까요?

3. 아니요, 아직 테스트는 해보지 못했어요. 이 부분은 테스트 해보고 다시 말씀드리도록 하겠습니다. (동작이 안 될 경우, 제가 제안 드린 방향 - 즉, CDATA를 AND 조건문에 거는 형태로 진행해야 한다는 건 확인했어요.)

4. 넵, 감사합니다 👍🏻 

5. 아하, 레퍼런스라고 해봐야 사실 별건 아니구요. 그냥 처음 참고했던 블로그 링크를 말씀드렸던거였어요.
위 댓글에도 링크가 걸려있는데, [여기](https://epthffh.tistory.com/entry/Mybatis-%EC%97%90%EC%84%9C-CDATA-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0#google_vignette)입니다.

6. 오호, 부등호가 if 조건절 내부에 위치할 수도 있군요. 저희 코드에 있었네요, 공유해주셔서 감사합니다.

2023-11-08 15:46 UTC, eunbileeme commented on src/main/java/flab/project/data/dto/CommentWithUser.java
이 부분은 테스트를 해봤는데, 제가 문맥 상 @Getter와 매개변수 생성자의 역할을 순간 동일시했던 것 같아요.
제안주신 것처럼 @NoArgsConstructor + @Getter를 써야 올바르게 작동합니다.

우선 저는 AllArgsConstructor(= @AllArgsConstructor가 아닌 11L ~ 13L의 직접 작성한 매개변수 생성자) + @NoArgsConstructor조합이면 실행이 될 줄 알았어요.

1. final은 이전에 민욱님과 이야기했을 당시, Spring의 Jackson 라이브러리가 데이터를 직렬화/역직렬화할 때 방해가 되었던 요소 -> 따라서 제거
2. 이전에 단순히 직접 매개변수 생성자를 구현해놨었음
3. 따라서 기본 생성자가 필요하다는 오류에 따라 @NoArgsConstructor를 붙이면 해결?

일줄 알았는데, @Getter가 필요하다는 오류를 내뱉더군요.

따라서 그냥 매개변수 생성자를 지우고 @Getter를 추가하고 동작시켜보니 잘 돌아가기 때문에,
기존에 직접 작성했던 매개변수 생성자는 지웠습니다.

2023-11-08 15:53 UTC, eunbileeme commented on src/main/java/flab/project/controller/CommentController.java
> +        if (limit > MAX_LIMIT) {
1. 혹시 어떤 원인으로 ConstraintsViolationException이 던져질거라고 생각하셨나요? 검색해보니 제약 조건 위반이라는데, 잘 와닿지 않기도 하고 원인이 광범위해서 여쭤봅니다.
- 위와 별개로 ConstraintsViolationException -> INVALD_USER_INPUT이 자동으로 처리 vs 내가 직접 수동으로 처리하는 부분에 대해서는 멘토님께 피드백을 받은 방향으로 바로 수정해서 아직 생각해보지 않았어요. 지금으로썬 Controller에서 댓글을 가져오는 로직을 보았을 때, 직관적으로 올바르지 않은 limit구나라는 걸 파악할 수 있는 좋은 가독성을 제공한다는 장점밖에 떠오르지 않네요.
2. 아니요, 위에서 말씀드린 것처럼 문제인 상황은 아니에요. 왜냐하면, 8개만 남았다면 그냥 8개만 보내줄거잖아요? (예외는 안 나겠죠..? 아마 안 날거에요.)
따라서 그냥 limit가 기본값이 10이어도 항상 10이라는 값이 경우에 따라 유지가 안 될 수도 있다는 가정을 설명드리기 위해 든 예시일 뿐이에요/

2023-11-09 02:27 UTC, J-MU commented on src/main/resources/mapper/flab/project/mapper/comment-mapper.xml
> +
1. CDATA까지 같이 있는 게 보기 더 싫긴 한데 CDATA자체에 드는 불편함은 CDATA를 처음 봐서일 거 같고. 일단 기본적으로 두 개가 중첩되어 있으니 보기 불편한거 같아요. Java코드 짤 때도, if문 두 번 중첩되면 보기 안 좋잖아요?
5. 아 그냥 블로그 글이였군요. 확인했습니다.

2023-11-13 00:33 UTC, J-MU commented on src/main/java/flab/project/controller/CommentController.java
> +        if (limit > MAX_LIMIT) {
1. @valid어노테이션을 썼는지, @validated어노테이션을 썼는지에 따라 달라지지싶은데 확실하지 않아요. 테스트 해보시는걸 추천드립니다.
2. 은비 님이 말씀하신 것 처럼, 댓글이 8개만 남았다면 그냥 8개만 보내주게 됩니다. 남아있든 댓글의 양에 따라 LIMIT이 바뀔 이유가 없어요. LIMIT은 의미상 "최대 N개 까지 보내라"라는 의미니까요. 따라서 LIMIT은 항상 10이지 남아있는 댓글에 따라 LIMIT의 크기가 바뀔 이유가 없어요. 이런 맥락에서 왜 유저에게 LIMIT을 받아오는지, 그냥 서버에서 상수로 LIMIT=10을 가지고 있으면 안되는 지에 대한 부분을 여쭤봅니다.

2023-11-15 04:31 UTC, eunbileeme commented on src/main/java/flab/project/service/CommentService.java
> +    }
오, 좋은 정보 감사합니다.
누락된 부분에 대해서는 알려주신 아파치의 StringUils 클래스의 isBlank()를 사용하도록 할게요.

그런데, 직접 작성하기보다 사용하시는 걸 권장하시는 까닭이 무엇이었나요?

2023-11-15 04:42 UTC, J-MU commented on src/main/java/flab/project/service/CommentService.java
> +    }
isBlank()와 같은 기능은 매우 자주 사용될 기능이라 Util클래스로 만들어줘야 할 텐데.. 이미 있는 기능을 굳이 저희가 구현할 필요가 없으니까요. Appache.common은 충분히 많은 사람들이 사용하고 있는 라이브러리라 검증된 라이브러리로 볼 수 있으니 가져와서 쓰는게 더 옳다고 생각합니다.
물론 외부라이브러리를 사용하기 곤란한 환경이라면 이야기다 달라질 수도 있겠지만요.

2023-11-20 13:58 UTC, J-MU commented on src/main/java/flab/project/controller/CommentController.java
> +        if (limit > MAX_LIMIT) {
따로 회의에서 궁금증을 해결했으므로 resolve처리하겠습니다.

프론트에서 viewPort라는 개념을 알게 되어서 좋았어요. 감사합니다.

2023-11-20 14:06 UTC, J-MU commented on src/main/java/flab/project/service/CommentService.java
>      }
위 코드에서 validateComment는 댓글을 생성할 때만 쓰이는 검증 로직입니다.
댓글을 가져올 때는 쓰이지 않는 검증 로직이에요.
위 상황에서 validateComment는 적절하지 않은 네이밍이라고 느껴서 validateAddCommentRequest()정도로 메서드명 변경을 제안드립니다.

2023-12-07 04:40 UTC, J-MU commented on src/main/java/flab/project/controller/CommentController.java
> +                                               @RequestBody @NotBlank @Size(min = 1, max = 1000) String content) {
다른 파라미터는 냅두고 왜 content만 RequestBody로 빼셨나요?

2023-12-07 12:09 UTC, eunbileeme commented on src/main/java/flab/project/controller/CommentController.java
> +                                               @RequestBody @NotBlank @Size(min = 1, max = 1000) String content) {
### 2023.12.08 (Slack - am 12:00 ~ 01:00)

민욱님께서는 Dto를 만들지 않고, content를 RequestBody로 빼신 이유가 무엇인가요?를 하나의 객체로 만들어 RequestBody로 왜 두지 않았냐고 물으신 반면
저는 RequestBody에 객체뿐만 아니라 값 형태로 ~하나씩~ 파라미터 하나를 넘겨주는 형태도 가능하겠지? 싶어서 위와 같이 구현을 진행했네요.

결과적으로 논리적으로 문제되는 부분이 없다고 하셨으니, 위 형태는 유지하되 @f-lab-jason 멘토님의 의견도 궁금하네요!

2023-12-14 07:57 UTC, J-MU commented on src/test/java/flab/project/service/CommentServiceTest.java
> +
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 리뷰하면서 너무 재밌기는 했는데
appache.common의 RandomStringUtils.random()메서드를 이용하면 원하는 길이의 랜덤한 문자열을 생성할 수 있습니다.
![image](https://github.com/f-lab-edu/Prostargram/assets/46997074/be493ae4-56c5-4f3a-a1ee-0b2d4fa4d2ad)

[참고링크]
https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/RandomStringUtils.html

2023-12-16 02:46 UTC, f-lab-jason approved these changes

2023-12-16 02:46 UTC, f-lab-jason commented on src/main/java/flab/project/controller/CommentController.java
> +                                               @RequestBody @NotBlank @Size(min = 1, max = 1000) String content) {
세션때 잠깐 얘기한 것 같은데 지금처럼 body로 받는 파라미터가 하나뿐이면 별 문제없다고 생각해요. 물론 request param으로 했을때 길이와 관련해서 번거로운 일도 있을 수 있구요.

2023-12-16 02:46 UTC, f-lab-jason commented on src/main/java/flab/project/service/CommentService.java
> +        if (StringUtils.isBlank(content) || content.length() > 1000) {
몇몇 컨트롤러와 공유되는 매직 넘버가 있는데(content length나 아래 maxLimit같은) 이 친구들은 constant로 빼서 두 군데서 같은 내용을 쓰면 좋겠어요. (코드상에 constant를 모아놓은곳이 있었는지 기억이 나질 않네요..)

2023-12-17 19:14 UTC, J-MU commented on src/main/java/flab/project/service/CommentService.java
> +        if (StringUtils.isBlank(content) || content.length() > 1000) {
@eunbileeme 
올려주신 상수 분리 커밋은 단순히 private static final로 빼서 클래스 상단에 두셨는데, 멘토님께서는 컨트롤러와 공유되도록 하시길 원하신거같아요.

다만 저희가  컨트롤러쪽에서 검증을 어노테이션으로 진행하고있는데, 어노테이션에서는 제가알기로 변수값 사용이 안된다고 알고 있어요.  테스트 한번 해보시겠어요?

2023-12-31 04:39 UTC, eunbileeme commented on src/test/java/flab/project/service/CommentServiceTest.java
> +
### (2023.12.31)
ㅋㅋㅋㅋㅋ 아쉽지만 좋은 메서드가 있으니 수정해야겠네요, 감사합니다.

2023-12-31 04:40 UTC, eunbileeme commented on src/main/java/flab/project/service/CommentService.java
>      }
### (2023.12.31)
이해했습니다, 수정하도록 하겠습니다.

2023-12-31 04:43 UTC, eunbileeme commented on src/main/java/flab/project/service/CommentService.java
> +        if (StringUtils.isBlank(content) || content.length() > 1000) {
### (2023.12.31)
![image](https://github.com/f-lab-edu/Prostargram/assets/103405457/dab6b316-e517-4295-b409-227d350e13ad)

@f-lab-jason 
"상수로 뺀 후, 두 군데에서 같은 내용을 쓰면 좋겠어요."란 말이 이해가 가지 않았었는데, 민욱님께서 DM에서 보내주신 위 사진과 형태를 말씀하신 것이 맞으실까요?

추가로, constant를 모아놓은 곳..이라고 하면 따로 분리할 클래스 파일을 말씀하신 것이 맞으실까요?
맞다면, 따로 분리해놓은 파일은 없습니다.

2024-07-03 08:55 UTC, J-MU requested changes

2024-07-03 08:55 UTC, J-MU commented on src/main/java/flab/project/controller/CommentController.java
> +                                               @RequestBody @NotBlank @Size(min = 1, max = 1000) String content) {
1. userId의 경우 로그인 기능이 구현되기 전 PR이라 RequestParam으로 받고 있는 것 같은데, 머지 후 새로운 PR에서 JWT에서 읽어올 수 있도록 수정 부탁 드려요. (다음 미팅 때, 방법 알려드리겠습니다.)

2. 시간이 많이 지나 위 댓글의 문맥이 이해가 가지 않는데 설명부탁드립니다.
> 저는 RequestBody에 객체뿐만 아니라 값 형태로 하나씩 파라미터 하나를 넘겨주는 형태도 가능하겠지? 싶어서 위와 같이 구현을 진행했네요.

"RequestBod에 값 형태로 하나씩 파라미터 하나를 넘겨주는 형태" 라는게 무슨 뜻일까요?

3. 결과적으로 parentId를 왜 RequestParam으로 받으시려 하셨는지 궁금합니다.

2024-07-03 08:55 UTC, J-MU commented on src/main/java/flab/project/controller/CommentController.java
> +    // Todo 토론 게시물의 경우, 진영을 의미하는 enum 추가 예정
진영을 의미하는 enum은 해당 PR에서 추가하시고 머지 하는 게 좋을거같네요.

2024-07-03 08:55 UTC, J-MU commented on src/main/java/flab/project/data/dto/model/Comment.java
> +    private long userId;
Lombok을 사용하실 때, 필드의 순서를 바꾸시는 것은 주의하셔야 합니다.
혹시나 모르실까봐 노파심에 코멘트 남깁니다.
현재 해당 수정으로 만들어진 버그는 없어보입니다.

[참고 링크](https://kwonnam.pe.kr/wiki/java/lombok/pitfall)

2024-07-03 08:55 UTC, J-MU commented on src/test/java/flab/project/service/CommentServiceTest.java
> +        Comment comment = Comment.builder().postId(postId).userId(userId).parentId(parentId).content(content).build();
코드를 왜 한 줄로 정리하셨나요?

2024-07-03 08:55 UTC, J-MU commented on src/test/java/flab/project/service/CommentServiceTest.java
> +    void addReply_invalidParentId() {
다른 곳에서는 댓글을 comment로 표현하셨는데, 여기서는 reply로 댓글을 표현하셨네요. 이유가 뭔가요?
대댓글이라서 reply라 표현하시는거 같기도 한데.. reply가 대댓글이라는걸 표현하기엔 이상한거 같은데 생각이 다르신가요?

2024-07-03 08:55 UTC, J-MU commented on src/test/java/flab/project/service/CommentServiceTest.java
> +    void addComment_contentIsZero() {
content is zero보다는 blank같은게 더 올바른 표현아닐까요?

2024-07-03 08:55 UTC, J-MU commented on src/test/java/flab/project/service/CommentServiceTest.java
> +    @DisplayName("lastCommentId가 없을 경우, 즉 처음에 댓글을 가져올 수 있다.")
1. "lastCommentId가 없을 경우" 보다는 "lastCommentId가 null인 경우"는 어떨까요?

    null이 "없다"를 표현하는 것은 맞지만, 코드를 처음 봤을 때, "lastCommentId가 없을 경우"라고 적혀 있으면 이게 무슨 뜻이지? 고민하면서 내부 코드를 더 읽어봐야 이해할 수 있어요. 반면 "lastCommentId가 null인 경우"라 표현하면 내부 코드를 더 살펴보지 않아도 읽자마자 무슨 뜻인지 이해할 수 있을거에요.

2. "처음에 댓글"이라는 표현이 "첫 요청"이라는 의미로 봤을 때 틀린 말은 아닌데 조금 어색하지 않나요?

    "가장 최신 댓글들을 죄회한다"는 어떨까요?


정리하자면 "lastCommentId가 null인 경우, 가장 최신의 댓글들을 조회한다."로 수정하는 것을 제안드립니다.

2024-07-03 08:55 UTC, J-MU commented on src/test/java/flab/project/service/CommentServiceTest.java
> +        Long invalidLimit = 11L;
음수인 Id에 대해서
L:119에서는 negativeParentId
L: 191에서는 invalidPostId

크기,길이를 초과한 변수에 대해서
L: 148에서는 excessContent
L: 236에서는 invalidLimit

어디서는 구체적으로 표현하고 어디서는 뭉뚱그려서 표현하는 거 같은데 일관적이면 더 좋을거같아요.

2024-07-03 08:55 UTC, J-MU commented on src/test/java/flab/project/controller/CommentControllerTest.java
> +        String excessContent = "댓글 작성하기 API를 작성할 당시가 아닌, 댓글 가져오기 API를 작성하면서 추가된 검증이라 테스트하게 되었습니다. 근데 1000자 채우기는 좀 힘들어서 그냥 아무 내용이나 쓰고 있습니다. 이렇게 해도 되겠죠? 그냥 게임 속 더미 데이터라고 봐주세요. 컨텐트의 길이가 글자의 수랑 대부분 같을테니
여기도 RandomStringUtils를 이용하시면 좋을거 같습니다.

2024-07-03 08:55 UTC, J-MU commented on src/test/java/flab/project/controller/CommentControllerTest.java
> +    // Todo (2023.12.10) CommentController - 댓글 가져오기 API에 userId의 추가로, 추후 관련 테스트 코드 추가 예정입니다..
머지 전에 todo는 모두 해결 부탁드립니다.

2024-07-03 08:55 UTC, J-MU commented on src/test/java/flab/project/controller/CommentControllerTest.java
> +        Comment comment = new Comment(1L, 1L, null, "안녕하세요");
1. Comment의 1~4번 파라미터가 무엇 인지 인지하기 힘드시지 않나요?
저는 Builder를 이용해서 명시해주는 것이 더 옳다고 생각합니다.

2. 현재 그냥 단순 더미 CommentWithUser 객체가 필요한 것으로 보이는데 테스트를 위한 CommentWithUser객체를 만들어주는 메서드를 작성해보는 것은 어떠실까요?

2024-07-03 08:55 UTC, J-MU commented on src/test/java/flab/project/controller/CommentControllerTest.java
> +        CommentWithUser commentWithUser = new CommentWithUser(comment, basicUser);
여기도 위와 동일합니다.

2024-07-03 08:55 UTC, J-MU commented on src/test/java/flab/project/controller/CommentControllerTest.java
> +    @DisplayName("lastCommentId가 없을 경우, 즉 처음에 댓글을 가져올 수 있다.")
1. 다른 comment에서 언급한 것과 같이
"즉 처음에 댓글을 가져올 수 있다" -> "가장 최신의 댓글을 가져올 수 있다." 로 고치는 것이 더 명확하지 않을까요?

2. lastCommentId가 없을경우 보다는 lastCommentId가 null일경우가 더 명확하게 표현하는 것 같아요.

2024-07-03 08:55 UTC, J-MU commented on src/test/java/flab/project/controller/CommentControllerTest.java
> +    @DisplayName("lastCommentId가 있을 경우, 즉 댓글을 가져올 수 있다.")
1. "lastCommentId가 없을 경우" 보다는 "lastCommentId가 null이 아닌 경우"가 더 명확하게 표현하는 것 같아요.
2. "댓글을 가져올 수 있다"라는 표현은 아무런 의미가 없는 문장인거 같아요. "lastCommentId를 통해 해당 댓글 이전의 댓글들을 조회할 수 있다."정도는 어떨까요?

2024-07-03 08:55 UTC, J-MU commented on src/test/java/flab/project/controller/CommentControllerTest.java
> +                .andExpect(jsonPath("$.message").value(ResponseEnum.INVALID_USER_INPUT.getMessage()));
ResponseEnum들은 static import로 정리 해주는게 더 나아보이는데 어떻게 생각하세요?

2024-07-03 08:55 UTC, J-MU commented on src/main/java/flab/project/controller/CommentController.java
> +                                                              @RequestParam(defaultValue = "10") @Positive @Max(10) long limit) {
limit은 저희가 SQL문에서 사용하는 용어잖아요. 해당 API를 사용하는 대상은 프론트 개발자 분들인 만큼
limit보다는 pageSize와 같은 표현이 그 분들이 이해하시기 더 좋지않을까요?

2024-08-06 12:51 UTC, merged