Feat/#68 이메일 확인 기능 구현
f-lab-edu/Prostargram pull request #69
Opened 2023-11-07 17:54 UTC by eunbileeme

## 📢 관련 이슈
- [x] #68 

## 📃 작업 사항
- Redis를 Docker에 설치해서 실험해보려다가 오래 걸리는 관계로, local에 설치 후 재시도 할 예정입니다.

2023-11-08 00:48 UTC, J-MU requested changes

2023-11-08 00:48 UTC, J-MU commented on src/main/java/flab/project/service/EmailService.java
> +
EmailService에서 하는 일을 조금 덜어내도 좋을 거 같다고 생각하는데..

현재 EmailService에서 하고 있는 일은 아래와 같아요.
 1. Redis에 저장된 key중 email이 존재하는 지 여부 확인, 존재한다면 제거
 2. 인증 코드 생성
 3. email 작성
위 3개는 클래스를 조금 나눌 수 있을 거 같아요.
1번 기능의 경우 EmailService에 유지
2번 기능의 경우 VerificationGenerator.class에게 책임 전가
3번 기능의 경우 EmailWriter.class에게 책임 전가
의 형태가 어떨까 싶어요.

위와 같이 클래스를 나누는 것을 어떻게 생각하시나여?

(EmailWriter는 이름이 조금 고민되네요. EmailGenerator도 괜찮은 거 같구.. 이메일을 생성/작성한다는 의미를 가지는 이름이면 좋을거 같아요.)

2023-11-08 00:48 UTC, J-MU commented on src/main/java/flab/project/service/EmailService.java
> +
1. "utf-8", "html"은 static final 상수로 빼내는 게 좋을거 같습니다.
2. 60 * 5L -> magic Number는 피해주세요.
3. write Email에서는 이메일을 작성하는 일만 해야지 Redis에 데이터를 작성하는 일은 밖으로 나와야 할 거 같아요.
4. MimeMessage.RecipientType.TO -> TO , 앞의 내용들이 코드를 읽는데 딱히 도움을 주진 않는 거 같아서 그냥 static import로 TO만 남기는 건 어떨까요?

2023-11-08 00:48 UTC, J-MU commented on src/main/java/flab/project/service/EmailService.java
> +    }
"verificationCode", "email"은 상수로 빼주시는 게 좋을 거 같습니다.

2023-11-08 00:48 UTC, J-MU commented on src/main/java/flab/project/utils/RedisUtil.java
> +    }
existData -> isExist
가 더 낫지않을까요?

2023-11-08 00:48 UTC, J-MU commented on src/main/java/flab/project/config/RedisConfig.java
> +    }
setKeySerializer, setValueSerializer가 없네요? 이유가 있나요?

2023-11-08 00:48 UTC, J-MU commented on src/main/java/flab/project/utils/RedisUtil.java
> +    }
get()으로도 의미를 충분히 내포한다고 생각하는데 어떻게 생각하시나요?

2023-11-08 00:48 UTC, J-MU commented on src/main/java/flab/project/utils/RedisUtil.java
> +    }
delete()으로도 의미를 충분히 내포한다고 생각하는데 어떻게 생각하시나요?

2023-11-08 00:48 UTC, J-MU commented on src/main/java/flab/project/service/EmailService.java
> +    }
RandomStringUtils 대신 UUID를 도입한 이유는 외부 라이브러리를 사용하지 않아도 된다는 점에서
이점이 있다고 판단하신 걸까요?

2023-11-08 00:48 UTC, J-MU commented on src/main/java/flab/project/controller/EmailController.java
> +    }
1. 왜 sendVerificationCode에서는 email address가 query String이고 checkVerificationCode에서는 path Variable인가요? 순수하게 궁금해서 여쭤봅니다.

2023-11-08 00:48 UTC, J-MU commented on src/main/java/flab/project/service/EmailService.java
> +
emailSender.send(message)는 구글 서버로 요청을 보내고 응답이 올 때까지 blocking되는 거 맞나요?
이메일 전송을 비동기로 처리하는 것은 어떻게 생각하시나요?

2023-11-08 01:09 UTC, J-MU commented
[64번 PR](https://github.com/f-lab-edu/Prostargram/pull/64)과 겹치는 거 같은데, 64번 PR은 CLOSE하시면 될 거같습니다.

2023-11-08 01:26 UTC, J-MU requested changes

2023-11-08 01:26 UTC, J-MU commented on src/main/java/flab/project/controller/EmailController.java
> +public class EmailController {
해당 컨트롤러에서 하는 일은 EmailController보다는 VerificationCodeController 같은게 더 어울리는 거 같은데 어떻게 생각하시나요? EmailService도 제가 아래에 나타낸 것과 같이 클래스를 분리하면 VerificationCodeService같은게 더 잘 어울리는 거 같습니다.

2023-11-08 01:44 UTC, J-MU commented on src/main/java/flab/project/service/EmailService.java
> +
이메일이 이미 존재하는 이메일 인지를 이메일 전송 전에 검증 해줘야 하지 않을까요?

2023-11-08 01:49 UTC, J-MU commented on src/main/java/flab/project/service/EmailService.java
> +    }
![image](https://github.com/f-lab-edu/Prostargram/assets/46997074/0811ba1e-5761-4856-befa-04ff10dba3f9)

1. 음... validCode를 삭제하지 않는 것은 "다음 단계로" 버튼을 눌렀을 때, 유저가 이메일 인증을 완료했음을 서버가 확인하기 위함인가요?
해당 부분에 더 좋은 방법이 없을까 고민이 되는데 우선 의도가 궁금해서 여쭤봅니다.

2. Redis에 두 번 접근해야 하므로 비효율적인거 같긴 한데... 이메일 검증을 한 사람이다 라는 표식을 남겨줄 방법이 있으면 더 좋을 거 같은데.. 딱히 떠오르는 방법은 없네요. 멘토님은 두 번 검증 하는 방법을 추천하셨나요?

2023-11-08 02:17 UTC, J-MU requested changes

2023-11-08 02:17 UTC, J-MU commented on src/main/java/flab/project/service/EmailService.java
> +    }
인증 코드는  a-z : 26 + 0-9: 10 자리 당 36개의 경우의 수입니다.
36^7 = 11,120,967,936 대략 100억 개 정도로 경우의 수가 꽤 많기는 한데.. 5분 안에 BruteForce로 못 깰 정도는 아닌 거 같아요. 음.. 설령 경우의 수가 매우 많아 BruteForce로 깨기 힘들다고 하더라도 인증 코드 입력을 일정 회수 이하로만 시도할 수 있게 하는게 더 좋은 방식 인거 같습니다. 
따라서 3번~5번 정도로 검증 회수 제한을 두는 게 좋을 거 같은데 어떻게 생각하시나요? 해당 로직에 시간을 너무 써서 다른 기능을 구현 못해보시는 것도 안 좋으니 멘토님과 상의 해보시는 걸 추천드립니다.

2023-11-08 15:18 UTC, eunbileeme commented on src/main/java/flab/project/config/RedisConfig.java
> +    }
제가 참고했던 원본 코드에서 없었기에 그대로 누락된 것 같습니다, 다른 특별한 이유는 없어요.
차마 생각하지 못했던 부분인데, 짚어주셔서 감사해요.

그런데, 민욱님 Feat/#48 로그인 및 로그아웃 기능 구현에 RedisConfig 파일에서 StringRedisTemplate이 이미 있더군요.

현재 Feat/#68 과정 중 레디스의 key-value로는 String 타입인 이메일-인증코드가 쓰이므로 RedisTemplate 부분을 StringRedisTemplate으로 수정하도록 할게요.

2023-11-08 15:18 UTC, eunbileeme commented on src/main/java/flab/project/controller/EmailController.java
> +public class EmailController {
1. EmailController 대신 인증이 명시되어 있는 VerificationCodeController가 더 어울리는 것 같다는 거에는 동의해요. (멘토님께서도 동의하셨습니다 👍🏻)
왜냐하면 현재 EmailController에서는 이메일을 수단으로 쓰고 있을 뿐이고, 도메인은 인증이잖아요?
따라서 VerificationController로 수정할 예정입니다, 감사합니다.

2. 우선, Controller의 인증 코드를 생성하는 API와 검증하는 API를 분리하여 클래스를 분리하는 걸 제안주신게 맞을까요?
맥락 상, 단순히 Controller 클래스의 이름 변경을 제안주신건지 아니면 Controller 클래스도 분리하는 걸 제안주신건지가 헷갈렸어요.
- 만약 클래스 분리를 제안주신거라면, 그건 애매하다고 생각해요.
현재 Controller에서는 검증 관련된 로직들만 존재하고 있으니까요.

2023-11-08 15:18 UTC, eunbileeme commented on src/main/java/flab/project/service/EmailService.java
> +
1. 인증 코드를 생성하는 로직을 따로 클래스로 분리하는 건 좋은 것 같아요.
하지만, 다른 두 부분에 대해서는 나누지 않아도 될 것 같다고 생각이 되어요.
왜냐하면, 위 코멘트에서도 예시를 들었듯이 현재 EmailController와 EmailService는 (이름만 이메일이고) 검증을 수행하는 로직들을 수행하고 있기 때문에 더 쪼갤 이유는 없다고 생각을 했어요.

---

> emailSender.send(message)는 구글 서버로 요청을 보내고 응답이 올 때까지 blocking되는 거 맞나요?

2. 이 부분은 질문의 의도를 잘 파악하지 못했어요.
혹시 비동기를 말씀하시고 싶으셨던건가요, 아니면 블로킹을 말씀하시고 싶으셨던건가요?
처음엔 블로킹 그 자체를 여쭤보시는 것 같았는데, 다음 문장으로 비동기로 제안을 주셔서 둘 중 어떤 부분에 대해서 물어보시는건지가 헷갈려요.
또, 보통 [동기 + 블로킹 / 비동기 + 논블로킹](https://velog.io/@nittre/%EB%B8%94%EB%A1%9C%ED%82%B9-Vs.-%EB%85%BC%EB%B8%94%EB%A1%9C%ED%82%B9-%EB%8F%99%EA%B8%B0-Vs.-%EB%B9%84%EB%8F%99%EA%B8%B0) 형태로 쓰이는데 비동기 + 블로킹 형태를 제안주시고 싶으셨던건지도 궁금해요.

---

> 이메일 전송을 비동기로 처리하는 것은 어떨까요?

3. 혹시 이메일 전송을 비동기로 해서 얻을 수 있는 이점을 어떤 것이라고 생각하셨나요?
저희가 구글 서버에 유저의 이메일로 인증 코드를 보내달라고 요청을 보내고,
잘 보냈다는 응답을 받기까지 다른 액션을 할 만한게 있을지에 대해서 생각을 해봤을 때, 떠오르지가 않아서 여쭤봅니다.

---

> 지금 포스트맨으로 요청을 보내면 응답까지 몇 초가 걸리나요?

4. 포스트맨은 안 써서, Swagger.UI를 통해 인증코드를 전송해보았을 때는 5초가 걸립니다.

---

5. 아하, 헷갈렸던 부분인데 짚어주셔서 감사합니다.
```
if (redisUtil.existData(email)) {
            redisUtil.deleteData(email);
        }
```

위 코드를 통해 단순히 이메일로 인증코드를 보내고,
다시 인증코드 생성에 대해 재시도를 하는거면 이 로직에서 걸리지않을까? 라고 생각했는데..

말씀하신 것처럼, 이미 가입한 유저가 다시 회원가입을 시도한다는 상황은 가정하지 못했었네요, 수정하겠습니다.

2023-11-08 15:18 UTC, eunbileeme commented on src/main/java/flab/project/service/EmailService.java
> +    }
1. validCode를 verifyCode 메서드에서 비교를 진행한 후, 왜 삭제하지 않는지에 대해서 여쭤보셨던게 맞을까요? 맞다면, 이 부분은 요청이 정상적으로 처리가 되었다면 인증코드는 알맞거나 알맞지 않거나 - 즉, true or false를 반환하게 될거에요. (왜냐하면 verifyCode 메서드의 반환 타입이 Boolean 타입이니까요.)
따라서 클라이언트에게 응답으로 true or false를 보내주기만 하면 되니까 단순히 레디스에서 가져온 인증코드인 `validCode`를 삭제할 생각까지 들진 않았습니다.

2. 혹시 ●로 설명하신 아래 2가지 이유들은 어떤 상황을 가정하시고, 예시를 들어주신 걸까요?
- 이메일 검증을 마쳤다면, UI 상에서 "검증 완료"로 표시가 되었을텐데 이 상황에서 "다음 단계로"를 눌렀을 때 왜 "이메일 인증 유효 시간을 초과했다."라고 응답이 오는지 잘 모르겠어요.
- 같은 이유로, 이미 검증은 끝난 상황에 "다음 단계로"를 눌렀을 때, 해당 메서드가 왜 호출되는건지 이해를 하지 못했어요.
- 위 2개의 예시와 함께 마지막 예시에 대해서 멘토님과 이야기를 나눠봤을 때, 좋은 아이디어를 주셨어요.

---

사실, 제가 위 2가지 예시들을 이해하지 못한 까닭은 `"회원가입 1단계 폼"에서 "다음 단계로"를 눌렀을 때,
요청으로 무슨 값을 보내줄 것인지?`를 이해하지 못해서 그런 것 같아요.

따라서 이 부분에 대해서 3번째 예시와 함께 멘토님과 이야기를 아래와 같이 나눠봤어요.

예시는 회원가입 1단계 폼(자체 로그인)을 가정으로 설명드릴게요.

![image](https://github.com/f-lab-edu/Prostargram/assets/103405457/72c6e5e3-b999-499a-ac0c-6515e55d2aa9)

1. 유저가 이메일을 입력
2. 유저가 "인증 요청" 버튼을 누름
3. 유저가 인증코드를 입력
4. 유저가 "인증 확인" 버튼을 누름 -> 이때, 클라이언트는 서버에게 요청으로써 이메일과 인증 코드를 보냄
5. 레디스에 이메일과 검증 토큰을 각각 key-value로 저장
6. 서버는 클라이언트에게 응답으로써 성공과 검증 토큰을 넘김
7. 클라이언트(= 프론트엔드)는 이메일과 검증 토큰을 어딘가에 저장
8. 유저는 닉네임을 입력
9. 유저는 "중복 요청" 버튼을 누름 -> 이때, 클라이언트는 서버에게 요청으로써 닉네임을 보냄
10. ~~서버는 닉네임을 DB에 저장(USER 테이블의 username 이겠죠?)~~
11. 그리고 레디스에 닉네임과 검증토큰을 각각 key-value로 저장
12. 서버는 클라이언트에게 응답으로써 성공 및 검증 토큰을 보냄
13. 클라이언트는 닉네임에 대한 검증 토큰을 어딘가에 같이 저장함
14. 유저가 "다음 단계로" 버튼을 누름
15. 클라이언트가 서버에게 요청으로써 `이메일`, `닉네임`, `인증코드에 대한 검증토큰`, `닉네임에 대한 검증토큰`, `비밀번호`를 보냄
16. 서버는 검증 토큰들을 통해 회원가입이 완료되었다 or 실패되었다는 의미로 ok or no와 같은 응답을 보냄

위 과정에서 볼 수 있듯이, 검증 토큰을 통해 회원가입 1단계 API 기능을 구현해보시는 걸 제안을 주셨어요. (물론, 아직 이해를 100% 한 건 아니라서 내일 녹화본을 받고 다시 복기해봐야 해요. 검증 토큰을 어떤 식으로 키워드를 검색할 건지도 검색해봐야 하구요.)

따라서 위 과정에 의거하여 구현할 예정입니다.
- 참고로 검증 토큰을 이해할 때는 CSRF 토큰과 비슷한 느낌으로 이해하시면 될 것 같다고 말씀해주셨었어요.

2023-11-08 15:18 UTC, eunbileeme commented on src/main/java/flab/project/service/EmailService.java
> +    }
오.. 코테 공부를 열심히 하셨군요. 민욱님 코멘트 보고 브루트포스 알고리즘이 암호화를 깨는 방식의 일종으로도 불린다는 걸 알았어요.

검증 횟수에 관해서는 제한을 둘 필요가 있을까? 싶어요.
왜냐하면 예를 들어, 제(내)가 민욱님(타인)의 이메일로 몰래 가입을 하기 위해 인증 코드를 수없이 시도해서 깨기 위한 가정 말고는 검증 횟수를 둘 이유가 딱히 떠오르지 않았어요.
즉, 별다른 이유 없이 타인의 이메일로 가입하기 위한 경우밖에 생각나지 않았어요.

물론, 보안을 위해 하는게 좋긴 하겠지만 무조건 해야한다!라고 생각이 드는 부분은 아니라고 생각해요.
- 말씀하신 것처럼, 현재 제 레벨에서는 다양한 기능 구현을 하는 것이 중요하기 때문이라고 생각한 것도 있어요.

2023-11-08 15:18 UTC, eunbileeme commented on src/main/java/flab/project/service/EmailService.java
> +    }
오, 아니요. 그건 아니었어요. 하지만, 지금 보니 그런 이점이 있을 수도 있겠다고 생각이 드네요. (왜냐하면 말씀하신 것처럼 자바가 제공하니까요.)

우선, UUID를 도입하게 된 까닭은 실제 회사에서 UUID를 통해 이메일 인증 로직을 구현한다는 이야기를 개발자 지인분께 들어서에요.

그리고 찾아보니, 확실히 코드가 간단하다보니 가독성도 좋아서 도입하게 되었습니다.

2023-11-08 15:18 UTC, eunbileeme commented on src/main/java/flab/project/service/EmailService.java
> +
1 + 2 + 4.
ㅜㅜ 사실 자주 볼 부분은 아니다보니까 크게 신경을 안 썼는데 빼두도록 하겠습니다.
- static final
- 변수 도입
- static import..? (이 부분에 대해서는 슈도 코드를 남겨주실 수 있나요?)
로 빼두도록 할게요.

3. 레디스 동작 관련된 메서드로 따로 분리해서 호출하는 방향을 말씀하신게 맞으실까요?

2023-11-08 15:18 UTC, eunbileeme commented on src/main/java/flab/project/utils/RedisUtil.java
> +    }
1. 위 get(), 아래 delete() 모두 동의하구요, 수정해두도록 할게요. 그리고 exist()로 수정하도록 하겠습니다.
2. 오.. 인정합니다. template.hasKey(key)의 리턴값이 boolean일테니까 Boolean.TRUE.equals()는 삭제하도록 할게요.

2023-11-08 15:21 UTC, eunbileeme commented
왜 Feat/#62(64 PR)이 깃 그래프가 꼬였지 싶었는데, 내용이 동일해서 그런걸 수도 있을까요?

우선, 두 PR은 하는 기능이 다르기 때문에(Feat/#62 : 이메일 인증 API - 인증 코드 생성, Feat/#68 : 이메일 인증 확인 API - 인증 코드 확인) 둘 다 냅두고 싶은데, 깃 그래프가 꼬여서(= 62에서 68의 내용을 커밋한 것으로 확인되고 있습니다.).. 이 부분은 한 번 수정해볼려고 노력해볼게요.

만약, 수정하기 어렵다고 느껴지면 금요일날 Call 하겠습니다.

2023-11-08 16:09 UTC, eunbileeme commented on src/main/java/flab/project/controller/EmailController.java
> +    }
일단, [멘토님께서 제안](https://github.com/f-lab-edu/Prostargram/pull/64#discussion_r1370949051)주신 것처럼

![image](https://github.com/f-lab-edu/Prostargram/assets/103405457/b8479ca8-20eb-4301-8443-d8590b7ddb39)

이런 형태로 나타내게 하고 싶어서, `sendVerificationCode`에서는 address를 Query String으로 표현했어요.

그리고, checkVerificationCode()에서는 동적으로 address(= email)이 기입된 상태에서 뒤에 code만 Query String으로 표현하고 싶어서 위와 같이 진행했습니다.

혹시 잘못 이해한 내용이 있다면 정정 부탁드릴게요.

2023-11-08 23:39 UTC, J-MU commented on src/main/java/flab/project/service/EmailService.java
> +
1. 검증로직과 이메일 작성이 분리될 수 있는 책임이라 생각하지 않으시나요? 그렇다면 검증코드 생성과 검증은 왜 분리될 수 있는 책임이라 생각하셨죠?
2. 구글 이메일을 전송하는 로직이 blocking이라면, non-blocking+비동기로 수정할 필요가 있을거 같다라는 의미였습이다.
3.Swagger에서 검사할 때 5초가 걸리신다고 하셨잖아요? 그 이유입니다. 그럼 유저의 request는 5초동안이나 저희 서버에 머무는 거잖아요? 이게 서버에 걸리는 부하가 너무 크다고 생각했어요. 
또한 응답에 걸리는 시간이 구글 메일 서버 상태에 의존한다는 점도 문제라고 생각했습니다. 구글 메일 서버 상태가 안좋으면 저희 응답도 같이 느려지니까요. 가끔 이메일인증같은거 할 때, 한참이 지나서야(수십초~) 이메일이 도착하는 것과 같은 경험을 하신적 없으신가요? 그럼 저희 서버 응답도 같이 수십 초가 걸릴테니까요.
저희가 회원가입 할때, 흔히보는 것이 "이메일이 오지 않았나요? 다시 보내기"와 같은 기능이 있어요. 이런걸 봤을 때, 아마 실제 서버도 이메일 정송이 성공했는지를 확인하지 않을거라 예상했어요(이건 사실이 맞는지 멘토님이랑 이야기해보시는게 좋을거같아여ㅎ). 아마 단순히 구글메일서버로 요청을 던지능 행위만 서버에서 할거같아요.

2023-11-08 23:41 UTC, J-MU commented on src/main/java/flab/project/utils/RedisUtil.java
> +    }
isExist가 아니라 exist를 하시겠다는 뜻이 맞나요?

2023-11-09 01:22 UTC, J-MU commented on src/main/java/flab/project/controller/EmailController.java
> +public class EmailController {
아뇨 단순 클래스명의 변경을 제안 드린거에요.
>EmailService도 제가 아래에 나타낸 것과 같이 클래스를 분리하면 VerificationCodeService같은게 더 잘 어울리는 거 같습니다.

클래스의 분리는 Service단을 말씀 드린 것이고 API분리를 말씀 드린 건 아닙니다.

2023-11-09 01:24 UTC, J-MU commented on src/main/java/flab/project/controller/EmailController.java
> +    }
말씀에서 checkVerificationCode 메서드에서 address를 pathVariable로 작성하신 이유는 없는거 같은데 address를 pathVariable로 작성하신 이유는 뭔가요?

2023-11-09 01:29 UTC, J-MU commented on src/main/java/flab/project/service/EmailService.java
> +
3. 메서드를 새로 만들어 달라는 의미는 아니였구요 redisUtil.setDataExprie()가 sendVerificationCode()메서드로 빠져야 할 것 같다는 의미였습니다.

2023-11-09 02:09 UTC, J-MU commented on src/main/java/flab/project/service/EmailService.java
> +    }
UUID는 36글자를 반환하는데 그 중 7글자만 잘라서 사용한다는 것이 비 효율 적이라고 느껴져서 여쭤봤어요.

실제로 테스트 진행해보니 UUID는 300~400ns 정도 RandomStringUtils는 80~ 120ns정도로 1회 호출당 걸리는 시간이 워낙 미미해서 성능 이야기를 하기엔 의미가 없겠더군요.

따라서 그냥 편하신대로 사용하셔도 상관없을 거 같아요.

2023-11-09 02:32 UTC, J-MU commented
>우선, 두 PR은 하는 기능이 다르기 때문에(Feat/https://github.com/f-lab-edu/Prostargram/issues/62 : 이메일 인증 API - 인증 코드 생성, Feat/https://github.com/f-lab-edu/Prostargram/issues/68 : 이메일 인증 확인 API - 인증 코드 확인) 둘 다 냅두고 싶은데

위 PR에 인증코드 생성,확인 코드 모두 있는거 아닌가요? 맞다면 64번 PR을 남기는 이유가 뭐죠?

>왜 Feat/https://github.com/f-lab-edu/Prostargram/issues/62(64 PR)이 깃 그래프가 꼬였지 싶었는데, 내용이 동일해서 그런걸 수도 있을까요?

아뇨 상관없을거에요

2023-11-09 06:01 UTC, eunbileeme commented on src/main/java/flab/project/utils/RedisUtil.java
> +    }
넵, 맞습니다. 혹시 exist()보다 isExist()가 더 자연스럽다고 생각하시는 까닭이 무엇인가요?

2023-11-09 06:09 UTC, eunbileeme commented
> 위 PR에 인증코드 생성,확인 코드 모두 있는거 아닌가요? 맞다면 64번 PR을 남기는 이유가 뭐죠?

원래 제 의도대로면 Feat/#62에는 인증코드 생성 로직만 존재하고, Feat/#68에는 인증코드 생성 및 확인 로직만 있을거에요.
따라서 62의 내용이 68에 속한건 맞지만, 68에 추가된 내용이 있으니 별개로 두고 싶다는 의미였어요.

만약, 제가 말씀드린 형태로 PR에 파일이 구성되어있지 않다면.. 제가 잘못 commit을 해서 꼬인 걸 수도 있겠네요.

2023-11-09 06:11 UTC, eunbileeme commented on src/main/java/flab/project/controller/EmailController.java
> +    }
/verification/email/{address}에서 {address}에 유저의 이메일이 동적으로 할당되게 하려면 PathVariable로 두어야 한다고 생각했어요.
```
/verification/email/pask2202@gamil.com
```

이런 식으루요, 혹시 위 내용 중 제가 잘못 이해한 부분이 있을까요?

2023-11-09 06:18 UTC, J-MU commented on src/main/java/flab/project/utils/RedisUtil.java
> +    }
반환형이 boolean이다 보니 자연스럽게 is를 붙이게 되었고 또 지금까지 그렇게 봐오고 써왔던거 같아요. 은비님 질문덕에 의심되어 찾아보니 문법 상 잘못 된 네이밍 같네요. 덕분에 배우고 갑니다. 감사합니다.

참고한 링크: [블로그](https://jacking75.github.io/ETC_true_false_return_function_naming/)

2023-11-14 13:20 UTC, eunbileeme commented on src/main/java/flab/project/service/EmailService.java
> +
![image](https://github.com/f-lab-edu/Prostargram/assets/103405457/6b361b25-eb24-4ea9-80bf-95b16044eba2)

3. 이렇게 명시되어 있는데, 첫 번째 필드인 seconds에 대해서는 `초단위`가 맞는 것 같아요.

2023-11-21 04:54 UTC, J-MU commented on src/main/java/flab/project/service/EmailService.java
> +
1번에 대한 제 생각

1. 이메일 작성이 재활용 가능성이 없는가?
- 저는 아니라고 생각합니다. 비밀번호 재 발급이 가장 대표적인 이메일 작성 로직이 필요한 기능이죠. 해당 기능을 구현할 때 중복된 코드가 만들어질 가능성이 높아 보입니다.

2. 지금 당장은 필요 없지는 않나?
- 옳은 말이긴 합니다. 지금 당장에 있어서는 이메일 인증에서만 쓰이는 로직 입니다. 지금 당장의 나와있는 기획만 봤을 때는 이메일 작성은 "이메일 인증"이라는 기능에서만 쓰이는 로직입니다. 하지만 변경 가능성이 매우 높은 로직이라고 볼 수 있는 로직이며 애초에 책임을 분리할 수 있는 부분이라고도 봅니다.

3. 그때 가서 고치면 되지 않을까?
- 제가 느끼기엔.. 이상적이지만 가능할까 싶은 생각이 듭니다. 물론 그때 가서 고치기만 한다면 문제 없는 상황이긴 합니다. 하지만 로직을 작성하는 사람이 이런 로직이 다른 곳에 숨어있는지 여부를 알기는 어려운 일이라고 생각합니다. 물론 자세하게 살펴본다면 찾을 수야 있겠지만, "비밀번호 재발급"로직을 작성하는 개발자가 "이메일 작성"이라는 로직이 이메일 인증에 숨어있을 거라는 생각을 못한 채 비밀번호 재발급에 중복된 코드가 작성될 가능성이 매우 높다고 생각합니다.

4. 클래스 분리에 대한 제 생각
- 클래스를 분리하는 것의 기준이 현재 시점을 기준으로 여기에서만 쓰이고 있는가?는 기준이 되기 힘든거 같아요.
예측과 다르게 재활용을 하게되는 기획이 추가된다면 결국 서비스에 중복 코드가 발생할 가능성이 매우 높으니까요.
클래스가 미래에 다른 곳에서 쓰일 가능성이 높을까?는 합리적인 기준이 될 수 있다곤 생각하지만 여전히 의문이에요.
미래에 기획이 어떻게 변할 지 모르는 상태에서 현재의 예측이 틀렸다면 결국엔 앞에서와 같은 문제가 발생할 테니까요. 미래에 대한 정확한 예측이란게 과연 가능한가요?

클래스를 분리하는 기준은 책임이 나뉘어 질 수 있는 요소인가?를 기준으로 최소한의 크기로 클래스를 설계하는 것이 어떨까 하는 생각이 들어요. 클래스를 나눈 것이 비용이 많이 드는 행위 라고는 생각되지 않아요. 반면에 클래스를 나눔으로써 더 유연한 코드가 만들어 지지 않을까라는 생각이 들어요.

위 예시에서는 이메일은 말씀하셨던 것 처럼 "수단"에 불과해요. 인증이라는 기능을 위해 이메일을 수단으로 쓰는 상황이니 충분히 책임이 분리될 수 있는 상황으로 느껴져서 클래스 분리를 제안드렸습니다.

2023-12-16 03:04 UTC, f-lab-jason approved these changes

2023-12-16 03:04 UTC, f-lab-jason commented on src/main/java/flab/project/service/VerificationService.java
> +    private void verificationEmail(String email) {
nit: `validateEmail`

2023-12-16 03:04 UTC, f-lab-jason commented on src/main/java/flab/project/service/VerificationService.java
> +    private MimeMessage writeEmail(String email, String subject, String content) {
nit: write는 약간..전송까지 포함된 느낌이고 compose가 조금 더 적절하긴 합니다 🙂

2023-12-16 03:04 UTC, f-lab-jason commented on src/main/java/flab/project/service/VerificationService.java
> +        long duration = 60 * 5L;
nit: constant로 빼주시겠어요? 변수명에 단위도 있으면 좋겠구요

2023-12-16 03:04 UTC, f-lab-jason commented on src/main/java/flab/project/utils/RedisUtil.java
> +    public boolean exist(String key) {
nit: 그냥 `hasKey`가 메소드명인게 더 직관적이지 않을까요?

2023-12-16 03:04 UTC, f-lab-jason commented on src/main/java/flab/project/utils/RedisUtil.java
> +    public void setDataExpire(String key, String value, long duration) {
nit: 이것도 `setWithDuration`같은 이름이 더 낫지 않을까요?

2023-12-30 09:38 UTC, J-MU approved these changes

2023-12-31 04:36 UTC, eunbileeme commented on src/main/java/flab/project/service/EmailService.java
> +
### (2023.12.31)
추후 민욱님이 관련 내용을 공부하신 후, 다시 질문을 하실 예정.

2023-12-31 04:37 UTC, eunbileeme commented on src/main/java/flab/project/controller/EmailController.java
> +    }
### (2023.12.31)
기능 상 문제는 없으며 순수한 의견 공유를 위한 코멘트입니다.

2024-03-13 16:47 UTC, merged