Feat/#70 닉네임 중복 확인 기능 구현
f-lab-edu/Prostargram pull request #71
Opened 2023-11-14 11:53 UTC by eunbileeme

## 📢 관련 이슈
- [x] #70 

## 📃 작업 사항
- (한국, pm 9:00 기준) 테스트 코드는 제외하고 구현하였습니다, 단 기능은 옳게 동작하고 있습니다.
- 캐시는 로컬 레디스(윈도우)로 진행하였습니다.

### 2023.11.14
1. DuplicationController, DuplicationServcie, .. 등 클래스의 이름이 "중복"으로서 어색하다는 생각을 하고 있습니다.
- 즉, 중복 검증을 하는 기능임을 나타내기 위해서 "중복"이라는 이름을 붙였는데, 전후맥락 없이 해당 클래스 이름만 보았을 때는 중복 검증을 수행하는 것이 아닌 중복? 이라는 의문이 드는 것 같아요.
- 따라서 Feat/#68 이메일 검증 API와 합쳐야 할까? 라는 생각을 하고 있습니다. "검증"이라는 하나의 도메인 내에서는 겹치는 기능을 수행한다고 보고 있기 때문이에요.
2. 저는 기능을 분리하는 기준을 도메인이라고 본 뒤 해당 도메인에 알맞게 클래스 명을 붙여야한다고 생각하는데, 이 부분에 대해서 옳게 생각하고 있는지부터 궁금합니다.
3. 검증 토큰은 세션에서 말씀드린 것처럼 UUID를 자른 무작위 값을 사용하였습니다.

2023-11-15 02:22 UTC, J-MU requested changes

2023-11-15 02:22 UTC, J-MU commented on src/main/java/flab/project/service/DuplicationService.java
> +    }
1. code를 조금 더 정리할 수 있을 거 같아요.
- if-else문의 사용은 가독성 측면에서 그닥 좋은 방식은 아니라고 느낍니다. 해당 코드는 else문이 굳이 필요가 없습니다. if문을 만족하면 예외가 던져 지고 그 외에는 모두 else문이니까요. 따라서 아래와 같이 수정하면 좋을 거 같아요.
```
public String verifyDuplicateUserName(String userName) {
        validateUserName(userName);

        Integer count = duplicationMapper.countUserName(userName);
        if (count == null || count == 1) {
            throw new InvalidUserInputException("Duplicate userName.");
        } 
        
        String verificationToken = createVerificationToken();
        storeUserNameAndVerificationToken(userName, verificationToken);
        

        return verificationToken;
    }
```
- 위 코드에서 username이 중복인지 여부를 확인하는 것은 메서드로 빼는 것이 더 깔끔해 보여요.
그럼 아래와 같이 고쳐질 거 같아요.
```
public String verifyDuplicateUserName(String userName) {
        validateUserName(userName);
        validateNicknameDuplicationInDB();
        String verificationToken = createVerificationToken();

        storeUserNameAndVerificationToken(userName, verificationToken);
        return verificationToken;
    }
```

- nickName은 DB에 존재하는 지 여부도 검증해야하지만, Redis에 선점되지는 않았는지도 검증해야할 거 같아요.
따라서 아래와 같이 메서드를 추가해야할 거 같아요.
```
public String verifyDuplicateUserName(String userName) {
        validateUserNmae();

        String verificationToken = createVerificationToken();
        storeUserNameAndVerificationToken(userName, verificationToken);

        return verificationToken;
    }

   public void validateUsername(String username){
        validateUserName(userName);
        validateNicknameDuplicationInDB();
        validateNicknamePreemptionInRedis();
   }
```
- storeUserNameAndVerificationToken 메서드 명은 명료하지 못한 네이밍이라고 느껴져요. 음...
preemptNcikname (닉네임을 선점하다.)라는 메서드명은 어떨까요? 선점한다는 CS에서 흔히 나오던 단어니 의미 전달도 명확하다고 느껴서 **어떻게 느끼시는지 궁금해요.**

최종 코드는 아래와 같이 변경될거에요.
```
public String verifyDuplicateUserName(String userName) {
        validateUserNmae();

        String verificationToken = createVerificationToken();
        preemptUsername(userName, verificationToken);

        return verificationToken;
    }
```

2023-11-15 02:22 UTC, J-MU commented on src/main/java/flab/project/service/DuplicationService.java
> +        if (userName.length() < 1 || userName.length() > 16) {
String에 대한 null여부 체크, 빈문자열(""), 공백문자열("              ")체크가 빠진거같아요.

2023-11-15 02:22 UTC, J-MU commented on src/main/java/flab/project/service/DuplicationService.java
> +    }
UUID를 잘라서 쓰시는 이유가 뭐죠? 7글자는 토큰으로써 역할 하기엔 너무 적은 길이인거 같은데..
토큰으로 쓸꺼면 36자 모두 써도 상관없지않나요?

2023-11-15 02:28 UTC, J-MU commented on src/main/java/flab/project/utils/RedisUtil.java
> +
exist보다는 exists가 문법적으로 맞는 표현이라고 해서 이를 따르는게 좋을거 같아요.
![image](https://github.com/f-lab-edu/Prostargram/assets/46997074/1e0eb32d-cdc3-4e0c-a49b-961e24f5f662)

2023-11-21 15:34 UTC, eunbileeme commented on src/main/java/flab/project/service/DuplicationService.java
> +    }
이 부분은 회의 때 Redis의 저장 용량과 관련하여 `UUID를 자를 필요성이 있다는 것에 동의하시는 것`으로 결론을 내려도 될까요?

2023-12-17 19:03 UTC, J-MU commented on src/main/java/flab/project/service/DuplicationService.java
> +        if (StringUtils.isBlank(userName) || userName.length() < 1 || userName.length() > 16) {
isBlank에서 ""(빈문자열)을 처리해주는데 userName.length()는 필요없지않나여?

2023-12-17 19:09 UTC, J-MU commented on src/main/java/flab/project/service/DuplicationService.java
> +    private static final long MINUTES_FOR_DURATION = 60 * 30L;
```
public void setWithDuration(String key, String value, long duration) {
        ValueOperations<String, String> valueOperations = template.opsForValue();
        Duration expireDuration = Duration.ofSeconds(duration);
        valueOperations.set(key, value, expireDuration);
    }
```

Duration.ofMinutes()가 있던데 초 단위로 선언하신 이유가 있나요?

2023-12-18 01:00 UTC, f-lab-jason commented on src/main/java/flab/project/config/RedisConfig.java
> +    @Value("${spring.data.redis.host}")
이런 config 내용들은 어디에 있는건가요?

2023-12-18 01:00 UTC, f-lab-jason commented on src/main/java/flab/project/config/exception/DuplicateUsername.java
> +public class DuplicateUsername extends RuntimeException {
nit: `Duplicated...` (다른곳들도요)

2023-12-18 01:00 UTC, f-lab-jason commented on src/main/java/flab/project/controller/DuplicationController.java
> +public class DuplicationController {
어차피 user 관련 기능의 일부이니 UserController에 같이 있어도 될 것 같아요.

2023-12-18 01:00 UTC, f-lab-jason commented on src/main/java/flab/project/controller/DuplicationController.java
> +    @PostMapping(value = "/users")
이 endpoint는 결과적으로 rest API상에서 '회원가입'의 의미를 가지게 될텐데 그냥 `/verify-username`같은게 더 낫지 않을까 싶어요.

2023-12-18 01:00 UTC, f-lab-jason commented on src/main/java/flab/project/mapper/DuplicationMapper.java
> +    Integer countUserName(@Param("userName") String userName);
`int`가 아닌 `Integer`를 쓴 이유가 있나요?

2023-12-18 01:00 UTC, f-lab-jason commented on src/main/java/flab/project/service/DuplicationService.java
> +        if (count == null || count == 1) {
`countUserName`이 null이 나올 수 있는 케이스인가요?

2023-12-18 01:00 UTC, f-lab-jason commented on src/main/java/flab/project/service/DuplicationService.java
> +    private void preemptUserName(String userName, String verificationToken) {
preempt는 조금 어색한 것 같은데..그냥 reserve같은게 더 나을 것 같아요 🙂

2023-12-18 01:00 UTC, f-lab-jason commented on src/main/java/flab/project/service/DuplicationService.java
> +        if (redisUtil.hasKey(userName)) {
1. redis에 set 할때는 `userName + USERNAME_IN_REDIS_SUFFIX`로 하는데 redis 내용을 validate할때는 userName만 하는건 어떤 용도로 쓰신건가요?
2. 유저 A와 B가 둘 다 닉네임 silverrain으로 중복체크하면 둘 다 redis에는 `silverrain_verify`를 키로 저장할텐데 그럼 나중에 쓴 사람이 덮어쓰게 될거고 먼저 중복확인한 사람은 해당 닉네임을 못쓸텐데 그게 원하는 동작방식이 맞나요? 여기 전체 메소드들은 어떻게 테스트하신건가요?
3. redis에 있는 키는 왜 확인하는건가요? 예를 들어 유저 A가 같은 닉네임으로 중복확인을 여러번해도 여전히 가입가능해야할텐데 db가 아닌 redis에 들어있는 내용으로 중복확인을 할 필요가 있나요?

2023-12-18 01:00 UTC, f-lab-jason commented on src/main/java/flab/project/service/DuplicationService.java
> +            throw new InvalidUserInputException("Invalid userName.");
nit: 에러메세지가 어디는 한글이고 어디는 영어인데 통일해주면 좋겠어요

2023-12-18 01:00 UTC, f-lab-jason commented on src/main/java/flab/project/service/DuplicationService.java
> +    private static final long MINUTES_FOR_DURATION = 60 * 30L;
변수명은 `MINUTES...` 이고 값은 1800인데 그럼 TTL이 1800분 이라는 건가요..?

2023-12-18 12:52 UTC, eunbileeme commented on src/main/java/flab/project/config/RedisConfig.java
> +    @Value("${spring.data.redis.host}")
application.yml에 포함되어 있는 내용입니다.

application.yml 자체를 올리기엔 개인 정보가 많아서 올리지 않았었는데, 말씀하신 Redis와 Email과 관련된 부분은 부분적으로 아래와 같이 올려드리도록 하겠습니다.

```
spring:
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: # 제 이메일 계정
    password: # 제 이메일 계정 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
```

2023-12-18 13:16 UTC, eunbileeme commented on src/main/java/flab/project/config/exception/DuplicateUsername.java
> +public class DuplicateUsername extends RuntimeException {
다른 곳이라면 아마 `DuplicationController`, `DuplicationService`, `ResponseEnum의 DUPLICATE_REQUEST`등 Duplication 또는 Duplicate가 들어간 파일을 말씀하시는 것 같아요.

이때, `DuplicationController`와 `DuplicationService`, 그리고 `DuplicationMapper`, `duplication-mapper.xml`은 아래 코멘트에 의하면 User의 내용으로 포함시켜도 될 것 같다고 말씀을 해주셨죠.

따라서 위 파일들을 제외하고 Duplication 또는 Duplicate가 들어간 파일에서 `Duplicated...` (p.p 형태)로 제안을 주신 까닭은 무엇인가요?

현재 PR에는 닉네임 중복 확인 기능에 대한 파일들이 존재하죠.
그래서 "닉네임"과 "중복"이라는 키워드를 포함해서 지었는데, `중복닉네임`처럼 어색한 형태로만 이름을 짓게 되더군요.  따라서 "중복" 키워드를 제외해야하나 싶다가도, 핵심적인 행위를 빠트리는 것 같아서 아예 다른 키워드로 자연스럽게 짓기 위해 이름 변경을 고민하고 있었어요.
그런데, 멘토님께서는 중복이라는 단어를 유지하되 p.p 형태로 추천해주셔서 이유가 궁금하여 여쭤보게 되었습니다.

2023-12-18 14:02 UTC, eunbileeme commented on src/main/java/flab/project/service/DuplicationService.java
> +        if (count == null || count == 1) {
당시에는 유저가 생성을 시도하는 닉네임이 DB에 이미 있거나(= count : 1) DB에서 확인이 되지 않는 경우(= count : null), 두 경우로 나뉘어지지 않을까 싶어서 위와 같이 작성했던 것 같아요.

그렇다면, 혹시 멘토님께서는 어떠한 오류로 인해 DB에서 확인이 되지 않는 경우(= count : null)는 고려할 필요가 없다고 생각하까요?

2023-12-18 14:06 UTC, eunbileeme commented on src/main/java/flab/project/service/DuplicationService.java
> +    private void preemptUserName(String userName, String verificationToken) {
reserve는 `예약하다`만 알고 있었는데, `갖다` 또는 `보유하다`라는 뜻도 있었군요..
영어가 약한 저희에게 다양한 일상적인 단어들을 알려주셔서 감사합니다 😆

2023-12-18 14:12 UTC, eunbileeme commented on src/main/java/flab/project/service/DuplicationService.java
> +            throw new InvalidUserInputException("Invalid userName.");
기계적으로 에러 메시지를 작성하다보니 의식하지 못했던 부분이네요. `영어`로 통일하도록 하겠습니다, 감사합니다 😉

2023-12-18 14:14 UTC, eunbileeme commented on src/main/java/flab/project/service/DuplicationService.java
> +    private static final long MINUTES_FOR_DURATION = 60 * 30L;
ㅋㅋㅋㅋㅋㅋㅋㅋ 죄송합니다 ㅜㅜ;

최종적으로 `30분`을 표현하고 싶었는데, 60분 * 30분으로 이해하셨군요. `seconds`로 수정하도록 하겠습니다.

2023-12-18 14:53 UTC, eunbileeme commented on src/main/java/flab/project/service/DuplicationService.java
> +        if (redisUtil.hasKey(userName)) {
1. 접미사가 붙기 이전의 로직 같네요.
확인하지 못했던 부분 같은데, 짚어주셔서 감사합니다. `userName` + `userName + USERNAME_IN_REDIS_SUFFIX`를 합친 key로 검증을 수행하는 방향으로 수정하겠습니다.
2. `동일한 닉네임에 대해 여러 유저가 시도할 경우, key : 세션 id + 닉네임 - value : 토큰과 같은 구조로 세션 id로 유저를 구분하는 건 어떤가요?`라고 제안을 주셨던 부분이군요.
최종적으로 유저 A와 B 중 Redis가 아닌 DB에 선점을 성공한 사람이 닉네임을 가져가게 되겠지만, 말씀하셨던 것처럼 Redis를 기준으로 나중에 중복 확인을 시도한 사람이 가져가게 되는 건 옳지 않은 방향이에요.
로직에 추가 피드백을 반영하지 못함 + 테스트 코드를 작성하지 않음으로 인해 발생한 문제점인 것 같네요.
따라서 key : 세션id + 닉네임 - value : 토큰 (이때, 세션 id와 토큰은 UUID로 구현)로 구현한 후, 테스트 코드를 통해 진행하겠습니다.
3. 음.. 기존에는 `DB 이전에 Redis에도 이미 닉네임이 있다면, 해당 닉네임은 (1차적으로 선점을 당했으므로) 시도할 수 없다.`라는 가정 하에 진행을 했었어요.
하지만, 멘토님의 말씀을 듣고보니.. Redis에 해당 닉네임이 이미 있든 없든 결과적으로 DB에 저장이 되니까 Redis에 이미 있는 건 상관이 없겠다 싶은데, 이를 말씀하신게 맞으실까요?
- 맞다면, `닉네임 중복 확인`에서 확인의 대상은 Redis + DB가 아닌 DB로 이해되는데 맞는 내용일까요?

2023-12-18 20:51 UTC, f-lab-jason commented on src/main/java/flab/project/config/exception/DuplicateUsername.java
> +public class DuplicateUsername extends RuntimeException {
요건 약간 통상적으로 중복관련해서 pp형태를 더 많이 씁니다. duplicate도 사본의 뜻이 있긴하지만 다른 단어와 조합해서 쓰진 않거든요

2023-12-18 20:52 UTC, f-lab-jason commented on src/main/java/flab/project/config/RedisConfig.java
> +    @Value("${spring.data.redis.host}")
실제로 배포를 해야하면 어떻게 진행할 생각이셨나요? credential들을 설정파일에서 직접 쓰는게 아닌 vault 서비스등을 통해서 inject하는 방법을 생각해보면 좋을 것 같아요.

2023-12-18 20:53 UTC, f-lab-jason commented on src/main/java/flab/project/service/DuplicationService.java
> +        if (count == null || count == 1) {
쿼리의 결과값으로 null을 반환할 수 있는 케이스가 아닌 이상 고려하실 필요는 없습니다. db에서 뭔가 오류가 발생했다면 exception을 던지지 결과값으로 null을 던지지는 않으니까요

2023-12-18 20:54 UTC, f-lab-jason commented on src/main/java/flab/project/service/DuplicationService.java
> +    private static final long MINUTES_FOR_DURATION = 60 * 30L;
단위가 초라면 `DURATION_IN_SECONDS`같은 표현이 조금 더 좋습니다 🙂

2023-12-18 20:56 UTC, f-lab-jason commented on src/main/java/flab/project/service/DuplicationService.java
> +        if (redisUtil.hasKey(userName)) {
말씀하신대로면 '중복확인을 했다 = 닉네임을 선접했다'인데 이건 비지니스 로직으로 조금 이상한 것 같아요. 실제 중복확인은 db로만 하는게 맞다고 생각됩니다. 다만 같은사람이 같은 닉네임을 여러번 확인할경우는 캐시를 보는게 의미있다고 생각되는데, 저희 프로젝트는 고려하지 않아도 될 것 같아요.

2023-12-19 03:45 UTC, J-MU commented on src/main/java/flab/project/controller/DuplicationController.java
> +    @PostMapping(value = "/users")
Post Method에 /users가 부적절한 URI라는 것에는 동의합니다만 verify-username가 최선인지 궁금합니다.
RestFul에서는 동사를 사용하지 말 것을 권장한다고 알고 있습니다. 그럼에도 불구하고 verify-name으로 작명하신 것은 동사를 사용하지 않으면 API가 하는 일을 나타내기가 어렵다고 판단해서 그런건가요?
(저도 마땅히 다르게 나타낼 방법이 안떠오르네요..)

2023-12-31 04:56 UTC, eunbileeme commented on src/main/java/flab/project/config/RedisConfig.java
> +    @Value("${spring.data.redis.host}")
@f-lab-jason 
음.. 우선, 두 단어를 잘 이해하지 못해서 application.yml에서 key와 같은 private한 정보들을 숨길 수 있는 방법에 대해서 다른 개발자 분들께 여쭤보고 진행해보았어요.

1. 우선, `credential`과 `vault service`는 각각 어떤 예시를 생각하시고 말씀하신 걸까요?
- 각각 검색을 시도해보았지만, credential에 대한 명확한 예시는 확인하지 못했고 대신 context 상 key과 같은 중요한 정보들을 말씀하신게 아닐까?하고 유추했어요.
- 다음으로 vault service는 이 개념에 대한 다양한 예시가 있는 줄 알았는데, 검색을 해보니 [`valut`라고 하는 서비스](https://ingnoh.tistory.com/6)가 있는 것 같았어요.

![image](https://github.com/f-lab-edu/Prostargram/assets/103405457/6bbc0268-a091-432c-b9ae-1fb5fc3a338f)

2. 위와 같이 `environment variables`를 이용하여 key 값을 숨기는 형태는 어떤가요?
- 피드백 내용을 잘 이해하지 못해서 위와 같은 방법을 통해 시도했는데, 멘토님께서 말씀하신 방법이 위 방법은 아닌 것 같아서 정확히 여쭤보고 싶었어요.

2023-12-31 04:57 UTC, eunbileeme commented on src/main/java/flab/project/config/exception/DuplicateUsername.java
> +public class DuplicateUsername extends RuntimeException {
### (2023.12.31)
일반적인 관례였군요, 확인했습니다.

2023-12-31 05:01 UTC, eunbileeme commented on src/main/java/flab/project/controller/DuplicationController.java
> +    @PostMapping(value = "/users")
@f-lab-jason 
Restful API의 가이드 라인은 말씀하신 것처럼 강제가 아닌 권장이라 위와 같이 동사로써 적합한 상황을 나타낼 수 있는 경우에는 그냥 동사로 추천을 해주신 것 같긴 한데.. 정확한 의견이 궁금하네요.

2024-03-11 15:54 UTC, J-MU approved these changes

2024-03-12 15:42 UTC, merged