Feat/#66 프로필 피드 가져오기 기능 구현
f-lab-edu/Prostargram pull request #75
Opened 2023-11-27 12:11 UTC by eunbileeme

## 📢 관련 이슈
- [x] #66  

## 📃 작업 사항
### (2023.11.27)
- user-mapper.xml은 아래의 두 가지 이유로 인해 작업 중입니다.
-1. BasePost에 대한 ResultMap 작성 시, 내부 필드들이 Post 테이블과 전적으로 일치하지 않기에 Join을 통해 가져와야하나?
-2. 비단 프로필 피드만 가져오는 것이 아니라, 프로필 페이지의 다른 content도 가져와야하는걸까? (맞을거라고 예상 중)

2023-12-12 10:55 UTC, J-MU commented on src/main/java/flab/project/controller/UserController.java
> +            @Parameter(name = "lastProfilePostId", description = "가장 마지막으로 받아온 프로필 게시물의 id", in = ParameterIn.QUERY, required = false),
그냥 취향이긴 한데..
프로필 피드 가져오기 API에서 변수명을 굳이 lastProfilePostId로 하기보다는 lastPostId 정도로만 해도 괜찮지 않을까요? 변수명이 조금 긴 감이 있는 거 같기도 해서

2023-12-12 10:57 UTC, J-MU commented on src/main/java/flab/project/controller/UserController.java
> +    @GetMapping(value = "/users/{userId}/profile")
URL이 excel과 다른데 일부로 바꾸신건가요?

![image](https://github.com/f-lab-edu/Prostargram/assets/46997074/56f4e75b-c0fb-4faa-9116-7809015cd74c)

2023-12-12 10:58 UTC, J-MU commented on src/main/java/flab/project/service/UserService.java
> +        int maxLimit = 10;
static final로 빠지는게 더 좋을거같아요.

2023-12-12 11:48 UTC, J-MU commented on src/test/java/flab/project/service/UserServiceTest.java
> +    @DisplayName("lastProfilePostId가 없을 경우, 즉 처음에 프로필 피드들 가져올 수 있다.")
적당한 작문이 어려운 테스트 케이스네요.

지금 작성하신, "lastProfilePostId가 없을 경우, 즉 처음에 프로필 피드들 가져올 수 있다."보다는
"프로필 피드 API를 처음 요청하는 경우, lastProfilePostId = null로 요청한다." 정도가 어떨까 싶은데 어떻게 생각하시나요?

2023-12-12 18:11 UTC, eunbileeme commented on src/main/java/flab/project/controller/UserController.java
> +    @GetMapping(value = "/users/{userId}/profile")
넵, 맞습니다. 우선 바꾸게 된 계기와 순서는 다음과 같아요.

1. UI 상에서 프로필 피드를 가져오는 페이지 또는 화면은 다음과 같습니다.
![image](https://github.com/f-lab-edu/Prostargram/assets/103405457/3909b3f1-6a0b-4a1d-97eb-e758264cc89d)
2. 1에 따르면 프로필 페이지에 접근함과 동시에 피드(= 게시물들)가 노출됨을 알 수 있습니다.
3. 따라서 '프로필 페이지와 프로필 피드를 가져오는 API의 url은 동일해도 되지 않을까?'란 생각이 들었습니다.
4. 또한, 이전에 저희가 회의에서 이야기한 것처럼 feed = 여러 게시물(복수), post = 게시물(단수)에 따라 겸사겸사 기존 url에서 feeds의 s도 함께 삭제하면서 변경하게 되었습니다.

혹시 1. ~ 5.에서 제가 잘못 생각한 부분이 있다면 알려주세요!

2023-12-12 18:14 UTC, eunbileeme commented on src/test/java/flab/project/service/UserServiceTest.java
> +    @DisplayName("lastProfilePostId가 없을 경우, 즉 처음에 프로필 피드들 가져올 수 있다.")
맞아요, 사실 고민을 많이 했던 테스트 케이스이기도 해요.

말씀하신 것처럼 해당 테스트 케이스는 기존의 작문 방향(= 추상적으로 서술, ex. 댓글을 작성할 수 있다 / 프로필 피드를 가져올 수 있다)과 달리 - "lastProfilePostId가 없을 경우" 보다는 직관적으로 **lastProfilePostId = null"이라고 서술하는 게 좋겠네요 👍🏻

2023-12-16 02:50 UTC, f-lab-jason approved these changes

2024-01-02 11:27 UTC, eunbileeme commented on src/main/java/flab/project/controller/UserController.java
> +    @GetMapping(value = "/users/{userId}/profile")
### (2024.01.02)

1. 변경한 url이 기존에 없었던 url일 경우, 프로필 페이지를 가져오는 url과 동일해도 괜찮을 것이라 판단
2. 기존에 존재하는 url일 경우, 확인 예정

즉, 1 또는 2의 생각을 가지고 작업했던 내역이지만 slack에서 `url이 같으면 클라이언트가 해당 API를 호출했을 때, 2가지의 API가 다 호출되겠지?`란 의도를 가지고 작업한게 맞는지 확인 예정입니다.

2024-07-03 13:00 UTC, J-MU requested changes

2024-07-03 13:00 UTC, J-MU commented on src/main/java/flab/project/controller/UserController.java
> +                                                                   @RequestParam(defaultValue = "10") @Positive @Max(10) long limit) {
댓글 PR에서도 남겼었는데

해당 API를 쓰는 사용자는 프론트 개발자들 입니다. 반면 limit이란 단어는 SQL문으로 부터 가져오신 단어 같아요.
SQL에서 "limit은 데이터를 최대 몇 개 뽑아라"를 의미하니까요. 다만, SQL이라는 문맥 하에서는 명확한 단어가 맞지만 프론트 개발자들이 볼 때는 조금 뜬끔없는 단어라고 느껴요.

pageSize라는 이름을 사용하면 더 명확하지 않을까요?

2024-07-03 13:00 UTC, J-MU commented on src/main/java/flab/project/controller/UserController.java
> +    @GetMapping(value = "/users/{userId}/profile")
시간이 지나 히스토리가 기억나지 않아 댓글 남깁니다.
1. 왜 url을 /users/{userId}/profile로 수정하셨나요? GET /users/{userId}/profile이면 프로필 정보를 가져오는 거겠구나 라고 느낄거 같아요. RestFull의 본질은 "결국 url을 보고 어떤 행위를 하는 api인지 알 수 있게 하자"라고 생각해요. 저는 해당 url을 보면 유저의 이름, 나이, 자기소개, 성별 등 프로필 정보가 나올 것이라고 예상되어 불분명한 표현이라고 생각이 듭니다.

2. 
>url이 같으면 클라이언트가 해당 API를 호출했을 때, 2가지의 API가 다 호출되겠지?란 의도를 가지고 작업한게 맞는지 확인 예정입니다.

이게 무슨소린가요..?

2024-07-03 13:00 UTC, J-MU commented on src/main/java/flab/project/controller/UserController.java
> +        List<BasicPostWithUser> profileFeed = userService.getProfileFeed(userId, lastProfilePostId, limit);
왜 BasicPostWithUser인가요?
토론 게시물도 프로필 피드에 노출될 수 있지 않나요?

2024-07-03 13:00 UTC, J-MU commented on src/main/resources/mapper/flab/project/mapper/user-mapper.xml
> +  </select>
일반 게시물에 대해서만 고려하고 짜신 쿼리문 같은데 토론 게시물의 경우는 어떻게 하실건가요?

2024-07-03 13:00 UTC, J-MU commented on src/test/java/flab/project/controller/UserControllerTest.java
> +    @DisplayName("프로필 피드 API를 처음 요청하는 경우, lastProfilePostId = null로 요청한다.")
"lastProfilePostId가 null이면, 가장 최신의 프로필 피드를 가져온다"는 어떠실까요? 이미 다른 PR에서 여러 번 이유를 언급해서 댓글 PR참고해주세요

2024-07-03 13:00 UTC, J-MU commented on src/test/java/flab/project/controller/UserControllerTest.java
> +    @DisplayName("프로필 피드를 가져올 때, lastProfilePostId가 양수가 아닐 경우 InvalidUserInput 예외를 반환한다.")
프로필 피드를 가져올 때, lastProfilePostId가 양수가 아닐 경우 ->
프로필 피드를 가져올 때, lastProfilePostId가 양수가 아니 라면

통일성 있게 가져가면 더 좋겠네요

2024-07-03 13:00 UTC, J-MU commented on src/test/java/flab/project/service/UserServiceTest.java
> +    @DisplayName("프로필 피드 API를 처음 요청하는 경우, lastProfilePostId = null로 요청한다.")
여기도 "lastProfilePostId가 null이면, 가장 최신의 프로필 피드를 가져온다"는 어떠실까요?

2024-08-07 06:21 UTC, J-MU commented on src/main/java/flab/project/controller/UserController.java
> +    @GetMapping(value = "/users/{userId}/profile")
회의 결과 URL수정하기로 결정

2025-01-22 08:55 UTC, J-MU commented
#254 PR에서 별도로 구현했으므로 Close합니다.

2025-01-22 08:55 UTC, closed without merging